### ISSUE TITLE
Port NatssChannel to cloudevents/sdk-go bindings

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/eventing-contrib#1041]
**Problem**
Now the `NatssChannel` dispatcher uses the `Client` APIs of cloudevents/sdk-go

**Exit Criteria**
`NatssChannel` dispatcher uses only the [bindings](https://github.com/cloudevents/sdk-go/tree/master/pkg/binding) APIs of cloudevents/sdk-go

**Time Estimate (optional):** 
1 week

**Additional context (optional)**
The new bindings API are designed to improve cpu/memory efficiency for transporting events.

You can use the KafkaChannel port as example: https://github.com/knative/eventing-contrib/pull/1039

/help-wanted
/good-first-issue

**Comment by pierDipi** [comment]
Stan binding implemented https://github.com/cloudevents/sdk-go/pull/322.
This issue needs an `sdk-go` release and then it's ready.

**Comment by n3wscott** [comment]
@pierDipi https://github.com/cloudevents/sdk-go/releases/tag/v2.0.0-prevew7

**Comment by pierDipi** [comment]
@n3wscott @slinkydeveloper https://github.com/knative/eventing/pull/2829
As a side note, the release name is mistyped

**Comment by pierDipi** [comment]
@slinkydeveloper @n3wscott https://github.com/knative/eventing-contrib/pull/1072
