### ISSUE TITLE
GitHubSource: Missing RBAC rules for mutating & validating webhook configurations

### ISSUE THREAD

**Issue by Fabian-K** [knative/eventing-contrib#1048]
**Describe the bug**
I´m installing the GitHubSource using the provided yaml of the release. Without modifications, the webhook controller prints the following errors:
````
E0320 09:29:15.291996       1 reflector.go:123] runtime/asm_amd64.s:1357: Failed to list *v1beta1.ValidatingWebhookConfiguration: validatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:knative-sources:github-webhook" cannot list resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
E0320 09:29:15.296806       1 reflector.go:123] runtime/asm_amd64.s:1357: Failed to list *v1beta1.MutatingWebhookConfiguration: mutatingwebhookconfigurations.admissionregistration.k8s.io is forbidden: User "system:serviceaccount:knative-sources:github-webhook" cannot list resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
````

Were the RBAC roles for this left out intentionally?

 **Knative release version**
I checked v0.13.2 and v0.12.3

Thanks,
Fabian

**Comment by Fabian-K** [comment]
Cool, thanks for picking this up! I think updating Secrets in the knative-sources namespace is also required.

**Comment by lionelvillard** [comment]
@Fabian-K which Secrets?

**Comment by Fabian-K** [comment]
I see the following in the logs.

```
[github-webhook-6bf7744f86-mw9bv] {"level":"error","ts":"2020-03-24T14:59:58.536Z","logger":"github-webhook","caller":"controller/controller.go:376","msg":"Reconcile error","error":"secrets \"sources-webhook-certs\" is forbidden: User \"system:serviceaccount:knative-sources:github-webhook\" cannot update resource \"secrets\" in API group \"\" in the namespace \"knative-sources\"","stacktrace":"knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:376\nknative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:362\nknative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:310"} 
```

Maybe those are the certificates to call the Webhooks?

**Comment by tom24d** [comment]
Hi guys,

I have seen same stuff and it seems that adding RBAC for WebhookConfiguration & Secret won't be enough. I mean it is needed for the future, but it gets temporary failure to crud GitHubSource if the PR is merged.

Here is what I've found.
First, it needs v1/Service for github-webhook. Couchdb has same structure so 400-webhook-service.yaml would help. 
Second, 500-webhook-configuration.yaml:27 should be same namespace for the service.
Once Service gets enabled, Create GitHubSource operation err gets changed:
`Post https://github-webhook.knative-sources.svc:443/defaulting?timeout=30s: service "github-webhook" not found`
to
`Post https://github-webhook.knative-sources.svc:443/defaulting?timeout=30s: no endpoints available for service "github-webhook"`.

Last, this is where I am stuck. To enable both configuration, the Service must be served with https. It needs TLS Certificate. 
According to these:
[https://medium.com/ibm-cloud/diving-into-kubernetes-mutatingadmissionwebhook-6ef3c5695f74](url)
[https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/](url)
They seem it is not related to Secrets/ServiceAccount. I am still a newbie and not familiar with security stuff, so not sure these approach would help.

Note that maybe couchdb gets reconcileErr for same reason.

 I hope this helps.
Thanks,
