### ISSUE TITLE
KafkaChannel: missing RBAC for webhook certs

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1049]
**Describe the bug**
https://github.com/knative/eventing-contrib/blob/6809717129cb7c917fe163397fb4f1a86aaff14e/kafka/channel/config/200-webhook-clusterrole.yaml#L32-L41

Is missing "update"

 **Expected behavior**
Webhook able to update config

 **To Reproduce**
Install KafkaChannel

 **Knative release version**
Tested in 0.11.3 but appears to also exist in future versions as well.

**Comment by pierDipi** [comment]
Fixed https://github.com/knative/eventing-contrib/pull/1082

/close
