### ISSUE TITLE
Kafka source silently drops events if they're not JSON

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#1050]
**Describe the bug**

When I send a message to my Kafka via:
```
echo bbbb | kafkacat -b mykafka:9092 -tmytopic
```
the message appears to be dropped w/o any kind of error message generated in the Kafka Source logs.  When I change `bbbb` to `{"msg":"foo"}` then it works. So it appears that the code is assuming that a msg w/o a content type is JSON and then something goes wrong after that.

 **Expected behavior**

Preferred: msg is sent to sink
Minimal: show an error about the msg if the source thinks it's bad or can't deal with it.

 **To Reproduce**
Put a msg in Kafka w/o a content-type and not formatted as JSON.

 **Knative release version**
HEAD

 **Additional context**

https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/message.go#L68
seems risky to assume that it's JSON if there is no content type.

/cc @aslom

**Comment by slinkydeveloper** [comment]
@duglin So do you think the preferred behaviour is sending the message to the sink without content-type?

**Comment by duglin** [comment]
@slinkydeveloper probably since it might be better to be silent than to lie about what the type is. However, I can't seem to reproduce the "silently drops" part of this any more. I thought I tested this from 'master' the other day but I might have been mistaken as it looks like it's working now.  I would close this issue but do you think the content-type aspect is something worth changing?

**Comment by slinkydeveloper** [comment]
I don't have a strong opinion on it.

@matzew wdyt?

**Comment by slinkydeveloper** [comment]
What I find curious is that cloudevents spec doesn't force an user to MUST set datacontenttype when data is set and viceversa, so dropping because it's "invalid" is not an option in this case because the produced event is still valid, even if it doesn't specify the content type

**Comment by slinkydeveloper** [comment]
Ok so, looking at the code and the [tests](https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/adapter_test.go), I think this is already fixed on master, no messages are dropped if missing the content-type or if they are not json.
However, if the content type is missing, it's assumed to be json. I'll open a PR for that
