### ISSUE TITLE
Kafka source: allow for parallelism

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#1051]
**Problem**
If ordering matters to application/user then the current processing of the Kafka event source makes sense - it will serialize the processing of events for a partition. However, if the application does not care about ordering then serializing the processing can then become a bottleneck.

I'm wondering if it would make sense to allow for two new config knobs on the Kafka Event Source:
1 - bool - allow the dev to choose between "serial" or "parallel" processing. Default "false" (serial).
2 - int - if "parallel" is chosen, max number of messages that should be processed at a time.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Event consumer

**Exit Criteria**
New flags

**Time Estimate (optional):**
2 for the core feature - perhaps more once we add in testing

**Comment by slinkydeveloper** [comment]
I don't get what parallelism means for you in this context. KafkaSource is based on sarama consumer groups, which spawns automatically one goroutine per partition. Then, the dispatch is done synchronously inside the "partition goroutine" aka no new message is processed from that partition until the previous message is handled. So where these two flags should act?

**Comment by duglin** [comment]
First, keep in mind that I'm relative new to Kafka so this may not make any sense within "normal" usage of Kafka, and if so then I'll just close this issue.  However, as I was playing with our Kafka eventSource I was trying to figure out the best way to configure things.

As you noted, sarama will create one go routine per partition, and then serializes all event processing within that go routine. And that makes perfect sense when the events in each partition might need to be processed in order.

So, I was then wondering about how to determine the right number of partitions. Reading a bit about it, while the is no definitive answer (obviously), a lot of the stuff I came across seemed to mention a relatively low number, like less than 10.  What wasn't clear to me is the reasons for keeping the number low, or making it larger, beyond the obvious desire to control the number of go routines on the consumer side. Is there something about the inner workings of Kafka that should influence this decision, or is it strictly a consumer threading issue?

Then I started to play with a usecase that didn't care about ordering, and I was processing a lot of events - in the millions. 5-10 partitions would be too slow for me. Increasing it to 250 partitions worked great! But is that a bad/risky config? Anyone know?

So, with all of that, it got me wondering if instead of playing a guessing game with the number of partitions (especially since once you increase it you can't ever decrease it), I was wondering if the Kafka EventSource could help here by pulling more than one event at a time from the partitions. So these two flags would be within the event source and would give the same net effect as increasing the # of partitions w/o actually doing so. But I'm also not sure this makes sense in a Kafka world.

**Comment by slinkydeveloper** [comment]
> Is there something about the inner workings of Kafka that should influence this decision, or is it strictly a consumer threading issue?

This depends on several aspects, both on client and on broker side. Look at this article: https://www.confluent.io/blog/how-choose-number-topics-partitions-kafka-cluster/

> So these two flags would be within the event source and would give the same net effect as increasing the # of partitions w/o actually doing so. But I'm also not sure this makes sense in a Kafka world.

A couple of months ago I experimented writing a dispatcher that asynchronously popped the message from the partition and then enqueue to dispatch it through http (https://github.com/knative/eventing-contrib/issues/608). The dispatch through HTTP lived in a goroutines pool bigger than the number of partition. The result was that the latency and thpt were worse than processing the partitions directly, b/c of too much cache invalidations (when a goroutine is spawned, there is no guarantee that is spawned in the same OS thread, which dramatically increases the cache invalidation).
This is probably worth another look now, given the new bindings API.

**Comment by markfisher** [comment]
if async concurrency is added on the dispatching side, how would the (per-partition) offset be managed? ordered processing within a partition and consumer-driven offset management per-partition go hand-in-hand, whereas for load-balancing off a shared queue, other messaging systems with that model would probably be a better fit

**Comment by duglin** [comment]
yea, this is where my newbie-ness with Kafka was shining thru and the more I played with kafka the more I was wondering if Kafka was the right choice for this particular customer.

Will probably just close this soon, but @markfisher let me ask you this....
one way I found to get the throughput I needed was to increase the # of partitions per topic. In particular, I made it around 200 and that seemed to give me much better results. However, that was just in a small test env so I was wondering if a large # of partitions is a bad idea in a real env? In my searching of the web most people seemed to talk about much smaller numbers (like 5-10) but I didn't know if that was just because they only needed that many or if it's because kafka doesn't like really large numbers of partitions.  Any insight here would be much appreciated. thanks!

**Comment by markfisher** [comment]
@duglin I think the article @slinkydeveloper referenced above is a good starting point:
https://www.confluent.io/blog/how-choose-number-topics-partitions-kafka-cluster/

This article describes some changes in 1.1 that significantly improve support for a high number of partitions in a cluster relevant to some of the tradeoffs discussed in the original (2015) article:
https://www.confluent.io/blog/apache-kafka-supports-200k-partitions-per-cluster/
(also: https://blogs.apache.org/kafka/entry/apache-kafka-supports-more-partitions)

Hope that helps!

**Comment by slinkydeveloper** [comment]
@duglin  can we close this?

**Comment by slinkydeveloper** [comment]
I'm gonna close it, reopen if you need it
