### ISSUE TITLE
Kafka source - comma or array for servers and topics

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#1055]
**Problem**

Today, for the Kafka event source, when people specify the list of bootstrap servers or topics, they're comma separated lists. When these lists get long (e.g. I'm messing with a usecase with ~100 topics), I'm wondering if a real array wouldn't be easier for people to manage.  And for consistency, I have the same question for the list of bootstrap servers.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**

Event consumer

**Comment by matzew** [comment]
yeah, sounds good ! 

/cc @lionelvillard

**Comment by lionelvillard** [comment]
@aslom

**Comment by aslom** [comment]
Is there a way to make it backward compatible? Supporting both string (for comma separated list) and array of strings?

**Comment by aslom** [comment]
Most popular configuration in Java Kafka application properties uses comma separated list: "bootstrap.servers: A list of host/port pairs to use for establishing the initial connection to the Kafka cluster. "

http://kafka.apache.org/documentation/#consumerconfigs
https://jaceklaskowski.gitbooks.io/apache-kafka/kafka-properties-bootstrap-servers.html

**Comment by duglin** [comment]
it should be easy to support both, but might look kind of funky. If the "normal" flow is to use a comma for some of these then ok. It just felt odd as I was playing with it - and I was adding over a 100 entries :-) 

I was thinking about the case where the yaml is in git and if someone changes something the "diff" will just show the entire long line and it might be hard to detect what changed. As separate lines it becomes easier.
