### ISSUE TITLE
Kafka source - allow for consumer group to be optional

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#1056]
**Problem**

Today the `consumerGroup` property on the Kafka event source is a required property. While I understand why it's important and while the Kafka library we're using (or even Kafka itself) might require a value, I'm wondering if we should make it optional for the KnEventing users.

If the user is only ever going to have one Event Source in that consumerGroup, then asking them to provide a value (when we could generate a unique value for them) would be a nice thing.

What do people think?

Proposal:
- make `consumerGroup` optional
- if not specified, then the controller creates a unique value for them
- the value (either from the user or generated) appears in the `status` section so the user can use it to debug stuff if necessary

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**

Event consumer

**Exit Criteria**

Ability to specify a Kafka event source w/o a consumerGroup.

**Comment by matzew** [comment]
seems reasonable to me

/cc @lionelvillard

**Comment by lionelvillard** [comment]
@aslom

**Comment by matzew** [comment]
perhaps we prefix it like `knative-kafka-source-FANCY_UUID`

**Comment by aslom** [comment]
Where would it be stored? Does it get preserved across pod restarts?

ALso it may be surprising for users - similar functionality question: https://stackoverflow.com/questions/43118671/kafka-consumer-default-group-id

**Comment by duglin** [comment]
One option is to store it in the CR's status section
