### ISSUE TITLE
Github resource deletion stuck when external webhook does not exist

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1058]
**Describe the bug**
The Github finalizer is not removed when the external webhook is not found.

 **Expected behavior**
The finalizer should be removed when 404 is returned when trying to delete the webhook

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by tom24d** [comment]
I would like to work on this.
Before that, I want to confirm about the step.
Did you delete the webhook manually on GitHub website after registering and get finalize loop(stuck)?

**Comment by tom24d** [comment]
In addition, it gets also stuck when Secret for webhook does not exist. Should it be removed then?

**Comment by lionelvillard** [comment]
thanks @tom24d for picking this up! TBH I don't know what I did. Might be I deleted the secret, not the webhook. Then the finalizer retries and try again to delete the webhook. Something like that.

/assign @tom24d
