### ISSUE TITLE
KafkaSource: Two controllers, statefulset and deployment

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1090]
**Describe the bug**
There are two KafkaSource controllers, one statefulset, and one deployment, there should be only one

 **Expected behavior**
When deploying KafkaSource there should be only one controller

 **To Reproduce**
Deploy KafkaSource.

 **Knative release version**
0.13.3

**Comment by lberk** [comment]
@grantr seems like the StatefulSet is still in the release yaml, but @matzew removed it in #989?

**Comment by lionelvillard** [comment]
The StatefulSet replicas count has been set to 0 for 0.13.x and will be completely remove in 0.14.
