### ISSUE TITLE
AwsSqsSource: cannot set sink to Kafka channel

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1100]
AwsSqsSource does not have the correct cluster roles to talk to a KafkaChannel.  I see a TODO in the comments that says:

TODO on these and the eventing ones that this should be replaced with an aggregated role for watching Addressables.
  - eventing.knative.dev

This task should be completed to allow AwsSqsSources to target KafkaChannels.

**Comment by n3wscott** [comment]
/good-first-issue

See how we use the addressable RBAC role in other components. search for "duck.knative.dev/addressable"

**Comment by IceIcebaby167** [comment]
My phone has been hacked. Can y'all help me on it.

**Comment by dongfsgf** [comment]
sorry.

**Comment by aditya69627** [comment]
Yes I wanna do it

**Comment by varunraj01999** [comment]
hi

**Comment by isuru87** [comment]
hi

**Comment by AceHack** [comment]
Any update?

**Comment by pierDipi** [comment]
@AceHack Is your issue fixed? 
That PR should fix it.

cc @lberk

**Comment by AceHack** [comment]
It appears to be fixed.  I'll open a new issue if not.
