### ISSUE TITLE
CamelSource should implement apis.Validatable and apis.Defaultable

### ISSUE THREAD

**Issue by mattmoor** [knative/eventing-contrib#1109]
cc @nicolaferraro @matzew 

Then we should set up the webhooks for these source types like in this PR: https://github.com/knative/eventing-contrib/pull/1107

**Comment by nicolaferraro** [comment]
Looks interesting. Unfortunately we had to leave some parts of the camel source unstructured because the Camel YAML DSL is not strictly defined yet, but there are other parts that can be validated.

**Comment by mattmoor** [comment]
This is mostly about validating and defaulting what you can, exhaustiveness isn't required.
