### ISSUE TITLE
Evaluate deprecation or handover of natss channel

### ISSUE THREAD

**Issue by davyodom** [knative/eventing-contrib#1130]
Current maintainers are considering withdrawing from ongoing maintenance of the natss channel. This issue is to gather information about interest in and adoption of the channel as well as looking for other possible maintainers.

**Comment by wallyqs** [comment]
Hi I'm one of the NATS maintainers and we can try to help with some of the maintenance. Thanks to @pierDipi for reaching out :)

**Comment by pierDipi** [comment]
I can help as well.

**Comment by davyodom** [comment]
Great news! I'm happy to set up anything useful to help facilitate a transition. We can also discuss in slack and the next eventing channels (aka event delivery) WG.

**Comment by wallyqs** [comment]
Thanks!

**Comment by davyodom** [comment]
@wallyqs let's talk in knative slack to carry this forward, or let me know if you will attend the event delivery wg calls

**Comment by wallyqs** [comment]
Thanks for following up @davyodom please send me an invite to wally@nats.io and can try to join too 🙏

**Comment by wallyqs** [comment]
Thanks @devguyio yes we're still interested, apologies this got stalled, need to prioritize it again. Think that for Jetstream we could do a different channel as well since

**Comment by TheJaySmith** [comment]
May make sense to start focusing attention towards JetStream. It seems like that's the direction NATS Streaming is going. I would be happy to assist in anyway that I can
