### ISSUE TITLE
Consider using only one consumer group in KafkaDispatcher

### ISSUE THREAD

**Issue by pierDipi** [knative/eventing-contrib#1166]
**Problem**
The `KafkaDispatcher` uses a consumer group per subscription and [this forces us to create a new `sarama.Client` for each of them](https://godoc.org/github.com/Shopify/sarama#NewConsumerGroupFromClient), otherwise, we have [parallelism issues](https://github.com/knative/eventing-contrib/issues/917).

Creating a new client isn't ideal because we create a new TCP connection pool to the Kafka cluster.

**Proposed solution**

`KafkaDispatcher` uses only one consumer group.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
[System Integrator](https://github.com/knative/eventing/blob/master/docs/personas.md#system-integrator)

**Exit Criteria**

`e2e` tests should pass with the flag `-parallel=12`

**Additional context (optional)**
https://github.com/knative/eventing-contrib/issues/917
https://github.com/knative/eventing-contrib/pull/1165

**Comment by slinkydeveloper** [comment]
I'm wondering... Can we invoke `ConsumerGroup#Consume` several times on the same instance of the `ConsumerGroup`? TBH it's not clear to me the lifecycle of `ConsumerGroup`, if it can be reused or needs to be destroyed several times...

**Comment by slinkydeveloper** [comment]
Ok `Close()` can't be invoked several times (i'm digging into the code of Sarama)

**Comment by slinkydeveloper** [comment]
Mh maybe what we should do is simply create more `ConsumerGroup` using `NewConsumerGroup`, in order to avoid sharing the client. What's your feeling about it  @pierDipi? I don't see any alternative

**Comment by pierDipi** [comment]
I would do the same.

**Comment by duglin** [comment]
I've noticed that when I scale the Kafka event source beyond 1, things will hang for a while and then start back up again. So in some testing, I would get flooded with events, then it'll pause for a few minutes, and then events would start to flow again - Kafka itself had a ton of events just waiting the entire time.  Could this behavior be related to this issue?

**Comment by slinkydeveloper** [comment]
> Could this behavior be related to this issue?

I'm not really sure because in kafka source the consumer group is always one and it's never destroyed and rebuilt (inside the same receive adapter instance), but i'm not confident enough to exclude it

**Comment by slinkydeveloper** [comment]
@duglin https://github.com/knative/eventing-contrib/issues/999

**Comment by pierDipi** [comment]
I'm re-opening the PR https://github.com/knative/eventing-contrib/pull/1165, I'll ping you when it's ready

**Comment by slinkydeveloper** [comment]
ok good, thank you!

/assign @pierDipi

**Comment by slinkydeveloper** [comment]
/close

Fixed by #1165
