### ISSUE TITLE
Enable Tracing in Github source

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/eventing-contrib#1198]
**Problem**
Enable Tracing configuration for Github source

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Event consumer/Event producer

**Exit Criteria**
Github source tracing works

**Time Estimate (optional):**
1

**Additional context (optional)**
In order to enable that, we just need to reflect the changes from https://github.com/knative/eventing/pull/3026.

An example on how to do that is provided by these changes to apiserversource:

* https://github.com/knative/eventing/pull/3026/files#diff-d99b024fa0cd240e5a9ba150e807531a
* https://github.com/knative/eventing/pull/3026/files#diff-d86a389c49e177be3527a5acd33138ae
* https://github.com/knative/eventing/pull/3026/files#diff-edbbfc473b7a21fb3031e92071dcca86

**Comment by MIBc** [comment]
Let me try.

**Comment by slinkydeveloper** [comment]
#1230 should be merged first

**Comment by lionelvillard** [comment]
moved to https://github.com/knative-sandbox/eventing-github/issues/103
