### ISSUE TITLE
Port Github source to adapter/v2

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/eventing-contrib#1199]
**Problem**
Github source still uses `knative.dev/eventing/pkg/adapter` module, which uses the cloudevents/sdk-go v1. We should port it to `knative.dev/eventing/pkg/adapter/v2`, which uses the new sdk-go

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Event developer/Event producer

**Exit Criteria**
Github source should not use anymore `knative.dev/eventing/pkg/adapter`

**Time Estimate (optional):**
1

**Comment by MIBc** [comment]
I can work on it.

**Comment by Abd4llA** [comment]
@MIBc are you working on this? Just checking since it's not assigned and we wanted to move #3103

**Comment by MIBc** [comment]
Yes. I will commit it as soon as possible.
