### ISSUE TITLE
Port Prometheus source to adapter/v2

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/eventing-contrib#1201]
**Problem**
Prometheus source still uses `knative.dev/eventing/pkg/adapter` module, which uses the cloudevents/sdk-go v1. We should port it to `knative.dev/eventing/pkg/adapter/v2`, which uses the new sdk-go

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Event developer/Event producer

**Exit Criteria**
Prometheus source should not use anymore `knative.dev/eventing/pkg/adapter`

**Time Estimate (optional):**
1

**Comment by MIBc** [comment]
I'd like to help.

**Comment by slinkydeveloper** [comment]
@MIBc thank you! I'll help to review, feel free to take inspiration from https://github.com/knative/eventing-contrib/pull/1202

**Comment by MIBc** [comment]
ok
