### ISSUE TITLE
Kafka event source IDs may not be unique

### ISSUE THREAD

**Issue by lance** [knative/eventing-contrib#1205]
**Describe the bug**
When receiving events from a Kafka event source, the event ID is a partition and offset. See here: https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/message.go#L57. That produces an ID that looks something like this: `"partition:1/offset:24"` which does not appear to be unique.

 **Expected behavior**
I expect Kafka event source events to have unique IDs such as a [v4 UUID](https://tools.ietf.org/html/rfc4122).

 **To Reproduce**
Receive an event from a Kafka event source and observe the value.

 **Knative release version**
Current

 **Additional context**
It appears that this is where the ID is set. https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/message.go#L57

**Comment by slinkydeveloper** [comment]
> That produces an ID that looks something like this: "partition:1/offset:24" which does not appear to be unique.

Did you ever managed to get two events with same offset and same partition? the couple of these two uniquely identifies a kafka message

**Comment by lance** [comment]
@slinkydeveloper is that guaranteed that no two messages will ever have the same partition/offset? If that’s true then yes this should be closed. I wasn’t aware of that guarantee.

**Comment by slinkydeveloper** [comment]
> is that guaranteed that no two messages will ever have the same partition/offset?

*on the same topic* yes, it's the way kafka can uniquely identify messages
