### ISSUE TITLE
CamelSource CI tests are failing

### ISSUE THREAD

**Issue by nicolaferraro** [knative/eventing-contrib#1250]
The e2e test is supposed not to do a full Camel K deployment but actually it should reuse an existing image. But it's not doing it, since [logs](https://00e9e64bac3dda2e72e464236afeff25203e2e3f589995dd6f-apidata.googleusercontent.com/download/storage/v1/b/knative-prow/o/pr-logs%2Fpull%2Fknative_eventing-contrib%2F1247%2Fpull-knative-eventing-contrib-integration-tests%2F1263078960732835840%2Fartifacts%2Fk8s.log.txt?qk=AD5uMEs_VxuOrhp2NPDhN7av31ZaXjghLliwwJu1KmDgfQzues-lmrEIAeMjzK4JiUE9FA_bqo0tp5_RrSj26tYlib6p_8WcPSG4Y0_hvgcA4b0S6YGZvcMzvSSceGAZ2ibgRb3q6blWu95h-5n_HuTXIrwQ66yMdSJaAEe_BprghulN5XMv91bG-fzNWi7JLq4k3erOZtunU8q0Wp_jiJJcVY3YwbGwOmZIbG5dLIarH9ea5-5f7XAu4jYw4DpcwxKibj8Wrh1wBc1qskqUxcFYx7fI5eRgGVIEJCgTAcpQEUcZXdkgI0xd1IaFtZTuKa6jS_U-DpyY1L6MK0U0hCkzDfYTh5C5TMDmv9AMTHGZwQ51QOACZXToVEZyI5nJZWBYdYY9FHCVPskHpBJOIVMYgfZTKOgyl3xH4WuSUvGwIuR7_9SLfh9dsE3COcU4QKyWLcre0rJ7f23dlILHASuJkJMuk4iDWEKgdHRXmJfCwMvpJKED8z2DZzL5Lo_RP6UlsPBgYS7veHLJfFpCcsr9tohq3mIKd8sGrYzNwuLZDu9CxlnWL9x3hKRrMmOzU9mNFXuh_LpXQbzIqw_gybjf1RJslgIHynDb8DUtjlpIIosF1if6jU3norH0A6KCg8QpAZnn3_2Xbe0pOsvR4u98WA7Kg9-H5IRMYw_zzN58VHhUe1CyT41bgIMZ7g6js8AtzcgHhsUpk2Fy5hn05U67b2wZHGN34V2lTN_uq7mICds_-2riJZZ5Ja1EnOkiNMP5stsGyNwbAB8KeZ3bSSCvr3pc8CraExv8L7usVqKjF7UiOrZZG2GpUMmKPUzknq1NNch72fJUbNntgwzHFW8q62iZ7wg4t9uwW7WubGoORh4C9bpzrJa9cOz3Dc-jAS5CLo04uUs2TzugOetST8zVdUnUbjbq0bW6AtGc5DoFa4l9xsRyvkJgwxfuH3rmV3HL_1nN6RqTS-dKZNMMhGI0wqE9mDOW5Q&isca=1) show that it's currently trying to build a new image (but no target registry is configured in the e2e tests).

**Comment by slinkydeveloper** [comment]
Related to https://github.com/knative/eventing-contrib/issues/990
