### ISSUE TITLE
Break apart the manager for each source controller into an independently releasable and installable controller

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-contrib#128]
## Expected Behavior

Sources are independently releasable, installable and updatable.

## Actual Behavior

Source manager is shared for all sources in eventing-sources making the shared controller deploy fragile. 

## Steps to Reproduce the Problem

  1. Install a source.
  2. Note the controller reconciles all supported sources.
  3. Note again that adding new sources adds complexity to the existing sources.

## Additional Info

We did this to move fast, and now have learned that it does let us move fast in development but it also slows us down for releases. Releases are more important.

**Comment by lionelvillard** [comment]
we did that.
