### ISSUE TITLE
KafkaSource Errors intermittently while posting to sink

### ISSUE THREAD

**Issue by lberk** [knative/eventing-contrib#1291]
**Describe the bug**
@Shashankft9 reported in knative/eventing#3230 that the kafka source intermittently.
 **Expected behavior**
kafkasource delivers the events reliably (or provides better observability messages)
 **Knative release version**
v0.14.0
 **Additional context**
@Shashankft9 would you be willing to elaborate on the overall throughput of the kafkasource?

**Comment by Shashankft9** [comment]
Hi, where do I have to look for this throughput? Some metrics etc? 

As for the times when I get error while sending the message (without any stat or benchmark): it happens quite often. I have to delete the kafkasource CRD and re-create it (sometimes couple of times) to make it work again. 
I'd happy to give you more information on this.

**Comment by Shashankft9** [comment]
My opinions of when it happens and why its happening: the error 100% comes up when I apply multiple kafksources through just one command, that is `kubectl apply -f source1.yaml -f source2.yaml`, although the error still comes randomly when I apply them separately. Sometimes I notice a time delay between the `Starting with config ...` logline and the `Starting partition consumer ...` logline and that is when the error definitely comes up. These are all based on my tests. Would be nice if you can reproduce at your end.

**Comment by Shashankft9** [comment]
I am getting this log in the `kafka-controller-manager` pod everytime I create the `KafkaSource`:

`{"level":"error","ts":"2020-06-03T07:58:06.581Z","logger":"kafka-controller","caller":"source/kafkasource.go:138","msg":"Unable to create the receive adapter{error 25 0 KafkaSource created deployment: \"default/kafkasource-kafka-source-90879364-6fdf-46ae-b332-4d4d0dbdbb08\"}","knative.dev/traceid":"6b86be08-b470-47ec-b2c4-afe16e375f38","knative.dev/key":"default/kafka-source","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/reconciler/source.(*Reconciler).ReconcileKind\n\tknative.dev/eventing-contrib/kafka/source/pkg/reconciler/source/kafkasource.go:138\nknative.dev/eventing-contrib/kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource.(*reconcilerImpl).Reconcile\n\tknative.dev/eventing-contrib/kafka/source/pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go:169\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20200519155757-14eb3ae3a5a7/controller/controller.go:434\nknative.dev/pkg/controller.(*Impl).RunContext.func2\n\tknative.dev/pkg@v0.0.0-20200519155757-14eb3ae3a5a7/controller/controller.go:372"}
`

went through the code here: https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/reconciler/source/kafkasource.go#L138

Seems like the deployment is being returned but with an error.

**Comment by pierDipi** [comment]
https://github.com/knative/eventing/issues/3230#issuecomment-643295539

/close
