### ISSUE TITLE
TestSingleBinaryEventForChannel and TestSingleStructuredEventForChannel are broken

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1310]
**Describe the bug**
These two e2e tests are failing.

**Comment by slinkydeveloper** [comment]
For which channel?

**Comment by lionelvillard** [comment]
I don't recall exactly. I think Kafka and NATSS.

**Comment by slinkydeveloper** [comment]
i'll try to reenable them for kafka, they should just work

**Comment by slinkydeveloper** [comment]
I think these are reenabled now on master

/close
