### ISSUE TITLE
Missing Logline for kafkasource 

### ISSUE THREAD

**Issue by Shashankft9** [knative/eventing-contrib#1317]
**Describe the bug**
I noticed that if I delete the sink, the kafkasource deployment does not log it at all, instead goes on to log this: https://github.com/knative/eventing-contrib/blob/41d31acf15f0ec903fb29f448446587bec8e6e8b/kafka/common/pkg/kafka/consumer_handler.go#L83 ONLY when an attempt is made to send a message to the topic.
Shouldn't there be some way of capturing when the linked sink has been deleted for a particular kafkasource and log it, for better debugging?

 **Expected behavior**
A logline should come up whenever the linked sink is deleted, and when its created again for that kafkasource deployment.

 **Knative release version**
v0.14.0

**Comment by slinkydeveloper** [comment]
> Shouldn't there be some way of capturing when the linked sink has been deleted for a particular kafkasource and log it, for better debugging?

I'm not sure there is a way, the kafkasource receive adapter doesn't monitor the deployments, so it can't know if the sink is up without sending it a message.

**Comment by Shashankft9** [comment]
What about using serving client to watch on all the ksvc CRDs, and whenever there is a DELETE operation on one of them, run through all the kafkasource CRDs checking which one mentioned that ksvc and then somehow go on to log it in the deployment of that kafkasource - I don't know how the logging part will be done, but I guess it will be similar to how message claiming and marking happens for each kafkasource deployment?

**Comment by slinkydeveloper** [comment]
> What about using serving client to watch on all the ksvc CRDs

That's not feasible for several reasons:

1. the sink could be anything `Addressable`, not necessary a ksvc
2. eventing components tries as much as possible to don't depend on serving

Also, I'm against the idea of having the receive adapter watch whatever sink because:

1. you're adding a cpu/memory load to the kafka source receive adapter, which doesn't effectively need to operate
2. this will need to assign some RBAC to kafka source 

What we could improve is the log message in receive adapter here https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/adapter.go#L138 wrapping the err into another error that describes verbosely that it can't send the event

**Comment by Shashankft9** [comment]
mhm got it. 

oddly, when the sink is deleted and I send the message, I directly get the log from https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/adapter.go#L142

and nothing from here: https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/adapter.go#L137

Is this intended?

**Comment by Shashankft9** [comment]
I mean if its not returned as an error but just as response status 404, then the log message improvement should be done here instead: https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/adapter.go#L142

**Comment by aliok** [comment]
Don't / can't we check the Sink's status if it is 'READY'? 
Not in RA though as RA only receives the URL of the sink at the moment but that could be improved.

**Comment by slinkydeveloper** [comment]
> Don't / can't we check the Sink's status if it is 'READY'?

I don't know, I expect the duck `Destination` should have such a field?!

**Comment by slinkydeveloper** [comment]
> Is this intended?

Probably not? But if that happens, I suppose this is something weird from the golang std lib (the message sender does nothing more than invoking the golang http client)

**Comment by lionelvillard** [comment]
What happens to the RA when the sink is deleted is currently unspecified (see https://github.com/knative/eventing/blob/master/docs/spec/sources.md). Something to bring up to the source WG.

/cc @n3wscott @nachocano @vaikas
