### ISSUE TITLE
Support AVRO decoding for kafkasource

### ISSUE THREAD

**Issue by alex3165** [knative/eventing-contrib#1319]
**Problem**
it would be nice if the kafkasource CRD could take an AVRO schema registry as a parameter and decode messages coming through accordingly the same way most kafka clients do, that would save lot of time having to do it in each functions

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Developers using Kafka with AVRO

**Exit Criteria**
Ensure that an AVRO encoded message is being decoded before invoking the knative function

**Time Estimate (optional):**
Golang already have multiple libraries to deal with decoding avro messages. The main logic for this feature would read the schema id and version from the binary message then fetch the schema given URL passed as parameter and decode the message before passing it to the function

**Comment by itsmurugappan** [comment]
I can work on this. /assign

**Comment by itsmurugappan** [comment]
@slinkydeveloper I thought this will be helpful in a couple of ways

1. To keep the ksvc's (Cloud event consumers) generic. (i.e. same consumer for different sources)
2. Will save the users from writing the same piece of logic to decode a kafka message in all the ksvc's, which includes fetching the schema id from kafka message and schema from an url.

@alex3165 please provide your thoughts as well.
