### ISSUE TITLE
GitLabSource stuck deleting when deleting namepace

### ISSUE THREAD

**Issue by makandre** [knative/eventing-contrib#1330]
**Describe the bug**

- created a GitLabSource custom resource in a namespace
- I then decided to remove the namespace
- Now the namespace is stuck in `terminating` phase (statuses below)
- I had to edit the GitLabSource yaml and remove the finalizer to get pass this.

```
{
    "lastTransitionTime": "2020-06-22T13:04:21Z",
    "message": "Some resources are remaining: gitlabsources.sources.knative.dev has 1 resource instances",
    "reason": "SomeResourcesRemain",
    "status": "True",
    "type": "NamespaceContentRemaining"
},
{
    "lastTransitionTime": "2020-06-22T13:04:21Z",
    "message": "Some content in the namespace has finalizers remaining: gitlabsources.sources.knative.dev in 1 resource instances",
    "reason": "SomeFinalizersRemain",
    "status": "True",
    "type": "NamespaceFinalizersRemaining"
}
```

 **Expected behavior**

When I delete the namespace the GitLabSources in the namespace should be able to cleanup without manual intervention

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by aliok** [comment]
I'm wondering if this is the case for other sources as well or only this one

**Comment by lionelvillard** [comment]
Could be the same issue we had with the GitHubSource: https://github.com/knative/eventing-contrib/pull/1089.
