### ISSUE TITLE
Use resolver.URIResolver in KafkaChannel

### ISSUE THREAD

**Issue by pierDipi** [knative/eventing-contrib#1388]
**Describe the bug**
KafkaChannel uses only the URI field of the `DeadLetterSink`: https://github.com/knative/eventing-contrib/blob/62ccf3743fbe0f1d0f8339e9636a85592880b7e9/kafka/channel/pkg/dispatcher/dispatcher.go#L147

 **Expected behavior**
KafkaChannel uses `resolver.URIResolver` for resolving `DeadLetterSink`.

 **To Reproduce**
Use `Ref` instead of `URI` in `DeadLetterSink`

 **Knative release version**
`<= devel`

**Comment by slinkydeveloper** [comment]
We don't need this, because it's already done by the subscription controller in eventing: https://github.com/knative/eventing/blob/master/pkg/reconciler/subscription/subscription.go#L558
