### ISSUE TITLE
KafkaChannel doesn't clean up consumer groups when the subscriber is removed

### ISSUE THREAD

**Issue by FWiesner** [knative/eventing-contrib#1389]
**Describe the bug**
When you remove a subscription (or `Trigger`) that affected a `KafkaChannel` then the consumer group is retained. @slinkydeveloper indicated that this is to allow later recreation of the same subscription. The consumer group is also disabled on the dispatcher, but the dispatcher seems to reopen the consumer group when it gets restarted. This leads to message delivery to the Broker (filter) where the Broker has no idea where to deliver the messages to as the Subscription is gone

 **Expected behavior**
Either the dispatcher should remember disabled consumer groups (for example using a ConfigMap) and keep those consumer groups silent over restarts or the consumer groups should be removed instead of just getting paused

 **To Reproduce**
Deploy a Trigger for a Broker with a KafkaChannel, then remove the Trigger again and check the consumer groups on Kafka

 **Knative release version**
0.15

 **Additional context**

**Comment by slinkydeveloper** [comment]
Any thoughts on this @lberk?
