### ISSUE TITLE
Security: Please set container Security Context on all Containers

### ISSUE THREAD

**Issue by ssandanshi** [knative/eventing-contrib#1390]
**Describe the bug**

Addressing possible security issues within the SQS Source and Kafka Source Containers.

(CIS_Docker_CE_v1.1.0 - 5.12) Mount container's root filesystem as read-only
(CIS_Docker_CE_v1.1.0 - 5.25) Restrict container from acquiring additional privileges

 **To Reproduce**
Security issues show up in Twistlock.

 **Knative release version**
0.16.0

 **Additional context**

<img width="1193" alt="Kafka" src="https://user-images.githubusercontent.com/13507608/87180010-b5982800-c2ad-11ea-8a86-26bb60a8e407.png">
<img width="1209" alt="SQS" src="https://user-images.githubusercontent.com/13507608/87180019-b8931880-c2ad-11ea-9cba-d678b213f5df.png">

Reference - #1098 
Open issue in knative/operator - https://github.com/knative/operator/issues/4

**Comment by ssandanshi** [comment]
Its now part of the milestones for the 0.17.0 release for Knative/serving (https://github.com/knative/serving/issues/7924). Can we add it to eventing and eventing-contrib as well?

**Comment by evankanderson** [comment]
Do you need to be able to set the securityContext for these pods, or would a pre-canned restrictive policy be sufficient?

I notice that there are some items that seem to be issues on the docker image? Are there issues with the image build, or simply the execution environment?

Proposed securityContext:

```yaml
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
```
