### ISSUE TITLE
[KafkaChannel] Use fanout config from Eventing

### ISSUE THREAD

**Issue by pierDipi** [knative/eventing-contrib#1413]
Use this fanout config https://github.com/knative/eventing/blob/master/pkg/channel/fanout/fanout_message_handler.go#L45 and then this function https://github.com/knative/eventing/blob/master/pkg/channel/fanout/fanout_message_handler.go#L93 does the job for you (so you can remove all the hacky code above for conversions)

_Originally posted by @slinkydeveloper in https://github.com/knative/eventing-contrib/pull/1408#discussion_r461670580_

**Comment by slinkydeveloper** [comment]
This might be connected to the work @aliok is already doing in #1407

**Comment by pierDipi** [comment]
This is fixed.

/close
