### ISSUE TITLE
Kafka Channel TSL Connection

### ISSUE THREAD

**Issue by LukasTomalla** [knative/eventing-contrib#1430]
**Problem**
We have already a Kafka Cluster, but it is only avaible with a TLS Connection. I don't find any documentation for a Kafka Channel with TLS Connection. It seems like only Kafka Source can have a TLS Connection

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Developer, System Integrator
**Exit Criteria**
Kafka Channel can etablish a tls connection

**Comment by itsmurugappan** [comment]
hi, did you check out the "Connecting to a TLS enabled Kafka broker" section in this https://knative.dev/docs/eventing/samples/kafka/source/
