### ISSUE TITLE
can not find the message sinking to the service

### ISSUE THREAD

**Issue by zhaogaiwen** [knative/eventing-contrib#1451]
**Describe the question**
when i send message to the topic through the command below，i can not find the consumer that consumes the message,what is more,i cannot find any error

bin/kafka-console-producer.sh --bootstrap-server 12.16.241.22:9092 --topic test

![image](https://user-images.githubusercontent.com/35682644/88353886-b9d64200-cd91-11ea-8b83-600ab7dcd371.png)

**Comment by slinkydeveloper** [comment]
@zhaogaiwen Can you set the logging in debug mode and provide a more verbose log? to do that, you need to change the `config-logging` config map in `knative-eventing` namespace and change level to debug and development to true
