### ISSUE TITLE
DockerHub and Docker Registry event source

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#1477]
It would be nice if there was a DockerHub and Docker Registry event source so that we can subscribe to, and receive, events related to images changing. I think this will be a critical piece in many CI/CD workflows.

**Comment by aliok** [comment]
@duglin @paulrossman 

Our GSoC student has already impelented DockerHub source: https://github.com/tom24d/eventing-dockerhub

cc @tom24d 

We just didn't have time to talk to the relevant WGs to move it to eventing contrib.

**Comment by tom24d** [comment]
I am happy to move to the org if source folks agree with :)

**Comment by aliok** [comment]
Ah, btw, https://github.com/tom24d/tekton-step-observer is also relevant for CI/CD workflows.
It is a project to enable cloud event emission on Tekton pipeline steps.

**Comment by lionelvillard** [comment]
@duglin the DockerHub source is hosted there: https://github.com/tom24d/eventing-dockerhub

**Comment by duglin** [comment]
any plans to move it under the knative community?

**Comment by lionelvillard** [comment]
@aliok @tom24d ^^^

**Comment by vaikas** [comment]
/close
@duglin I'm closing this since it most certainly won't be coming into this repo. Perhaps figure out if there's still interest in moving it to knative-sandbox/eventing-*
