### ISSUE TITLE
Please make a eventing-natss repo in knative-sandbox

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-contrib#1487]
solves the natss checkbox for https://github.com/knative/eventing-contrib/issues/1482

**Comment by evankanderson** [comment]
(This may eventually have a lot of functionality moved into NATSS upstream, except for the Knative-specific components.)

**Comment by grantr** [comment]
Duplicate of https://github.com/knative/community/issues/236

(that one has the standard format so will be easier to use as a tracking issue)
