### ISSUE TITLE
Delete Receiver Adapter deployment when sink is not found

### ISSUE THREAD

**Issue by itsmurugappan** [knative/eventing-contrib#1493]
**Problem**
Create a kafka source before creating the ksvc(which is the sink), kafka source wont create a deployment, this works as expected. But, after succesful reconciliation of kafka source, if ksvc is deleted, kafka source status goes to false, but pod is still up, trying to send messages to sink. 

In this scenario if we delete the deployment of receiver adapter, it will be reconciled back when the sink is back up.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Developer

**Exit Criteria**
Kafka source adapter deployment is deleted when sink is not found

**Additional context (optional)**
I tried these step manually and it works fine.

**Comment by grantr** [comment]
I think I would classify this as a bug:
> if ksvc is deleted, kafka source status goes to false, but pod is still up, trying to send messages to sink.

IIUC, the messages the receive adapter tries to send are not retried if the sink comes back, but are lost during the downtime.

**Comment by itsmurugappan** [comment]
yes, messages are lost.

**Comment by itsmurugappan** [comment]
@grantr can i send a PR to address this one or it needs more discussion ?

**Comment by grantr** [comment]
@itsmurugappan Yes please do send a PR! If you plan to work on this issue, please assign it to yourself so nobody else duplicates your work. Use the `/assign` command in a comment.
