### ISSUE TITLE
Error: "Trigger had a different UID"

### ISSUE THREAD

**Issue by mpeyrard** [knative/eventing-contrib#1520]
**Describe the bug**
I have configured two Knative Services to communicate with each other via Knative Eventing. Our system manually creates the broker via yaml files (as opposed to installing the broker via annotation), as well as the trigger. The broker is backed by the Kafka Channel that is provided under Knative contrib.  The service that produces the event does an HTTP POST to the broker address, which accepts the event with a 202 code. Using Kafka Tools, we have been able to confirm that the Cloud Event is deposited into the appropriate Kafka topic. However, the endpoint on the target service is never invoked. We have checked and re-checked that the ``CE-type`` attribute on the event matches the filter in the trigger. We have also double-checked that the endpoint on the target service is reachable by manually hitting it using postman. 

Upon investigating the logs in the broker filter logs, we find the error message:
```
{"level":"error","ts":"2020-07-17T21:26:02.692Z","logger":"broker_filter","caller":"filter/filter_handler.go:211","msg":"Error sending the event","commit":"02bc516","error":"trigger had a different UID. From ref '17feec3a-87cb-4bd7-b63d-e04148a28963'. From Kubernetes '3e6fb035-007b-46c2-ab68-58c0993866c9'","stacktrace":"knative.dev/eventing/pkg/broker/filter.(*Handler).serveHTTP\n\tknative.dev/eventing/pkg/broker/filter/filter_handler.go:211\nreflect.Value.call\n\treflect/value.go:460\nreflect.Value.Call\n\treflect/value.go:321\nknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/client.(*receiverFn).invoke\n\tknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/client/receiver.go:93\nknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/client.(*ceClient).obsReceive\n\tknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/client/client.go:168\nknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/client.(*ceClient).Receive\n\tknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/client/client.go:157\nknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/transport/http.(*Transport).obsInvokeReceiver\n\tknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/transport/http/transport.go:530\nknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/transport/http.(*Transport).invokeReceiver\n\tknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/transport/http/transport.go:514\nknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/transport/http.(*Transport).ServeHTTP\n\tknative.dev/eventing/vendor/github.com/cloudevents/sdk-go/v1/cloudevents/transport/http/transport.go:622\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2387\nknative.dev/eventing/vendor/go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\tknative.dev/eventing/vendor/go.opencensus.io/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890"}
{"level":"info","ts":"2020-07-17T21:26:02.693Z","logger":"broker_filter","caller":"filter/filter_handler.go:237","msg":"Unable to get the Trigger","commit":"02bc516","error":"trigger had a different UID. From ref 'fd3a2ec2-a63f-4fcb-b60c-1070f98bf77c'. From Kubernetes '3e6fb035-007b-46c2-ab68-58c0993866c9'","triggerRef":"default/detector"}
```

I am not currently certain if this is a bug or some kind of misconfiguration on my end. However, if we assume that it is the latter, then this error message has not been very helpful in figuring out what is wrong. 

Since it seems to be complaining about my Trigger specifically, I'll copy it here:
```
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: {{ .Chart.Name }}-trigger
  namespace: {{ .Values.global.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart/name: {{ .Chart.Name }}
    chart/version: {{ .Chart.Version }}
spec:
  broker: signal-rule-broker
  filter:
    attributes:
      type: signals.seismic.rules.detection
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: {{ .Chart.Name }}
```

 **Expected behavior**
We expected the Cloud Events to arrive at the configured destination.

 **To Reproduce**
 With the current state of my project, this is what I'm doing to reproduce it:
- Install a Knative broker that is backed by the Kafka Channel.
- Set up two Knative Services. In my case, one is called ``detector`` and the other is called ``router``. The detector looks at sensor data and sends Cloud Events to the router via the broker when a pattern is found. But I would expect simple placeholder services to suffice.
- Install a trigger that filters on the ``CE-type`` of the detection event, with the ``router`` service as the target.
- Insert some test data into the ``detector`` that causes it to trigger a detection event.

As stated above, the cloud event finds its way into the Kafka Channel's kafka topic for the broker, but no further. Furthermore, errors appear in the brokers' filter pod logs complaining about "trigger had a different UID". 

 **Knative release version**
0.14.1

**Comment by slinkydeveloper** [comment]
Hey people, I'm going to give look at this soon

/assign

**Comment by slinkydeveloper** [comment]
@MPeyrard86 which version of eventing are you using?

**Comment by MPeyrard86** [comment]
@slinkydeveloper We are still using 0.14. But we're probably due for another upgrade.

**Comment by grantr** [comment]
Possibly related to https://github.com/knative/eventing-contrib/issues/1560

**Comment by vaikas** [comment]
Ok, so tried to repro this from the head with those steps and I couldn't:



```
vaikas-a01:eventing-camel vaikas$ cat ~/repro-1520/broker.yaml
apiVersion: eventing.knative.dev/v1beta1
kind: Broker
metadata:
  name: repro
  namespace: default
vaikas-a01:eventing-camel vaikas$ cat ~/repro-1520/trigger.yaml
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: default-test-trigger
  namespace: default
spec:
  broker: repro
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: event-display
vaikas-a01:eventing-camel vaikas$ kubectl create -f ~/repro-1520/broker.yaml
vaikas-a01:eventing-camel vaikas$ kubectl create -f ~/repro-1520/trigger.yaml
trigger.eventing.knative.dev/default-test-trigger created
vaikas-a01:eventing-camel vaikas$ kubectl get brokers
NAME      URL                                                                      AGE     READY   REASON
default   http://default-broker.default.svc.cluster.local                          6d18h   True
repro     http://broker-ingress.knative-eventing.svc.cluster.local/default/repro   8s      True
vaikas-a01:eventing-camel vaikas$ kubectl get triggers
NAME                   BROKER    SUBSCRIBER_URI                                   AGE     READY   REASON
default-test-trigger   repro     http://event-display.default.svc.cluster.local   10s     True
ping-trigger           default   http://subscriber.default.svc.cluster.local      6d18h   True
vaikas-a01:eventing-camel vaikas$ kubectl get imc
NAME                URL                                                             AGE   READY   REASON
my-channel          http://my-channel-kn-channel.default.svc.cluster.local          76d   True
my-channel-2        http://my-channel-2-kn-channel.default.svc.cluster.local        76d   True
repro-kne-trigger   http://repro-kne-trigger-kn-channel.default.svc.cluster.local   33s   True
vaikas-a01:eventing-camel vaikas$ kubectl get imc repro-kne-trigger -oyaml
apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
metadata:
  annotations:
    eventing.knative.dev/scope: cluster
    messaging.knative.dev/creator: system:serviceaccount:knative-eventing:eventing-controller
    messaging.knative.dev/lastModifier: system:serviceaccount:knative-eventing:eventing-controller
    messaging.knative.dev/subscribable: v1
  creationTimestamp: "2020-09-16T17:46:04Z"
  generation: 2
  labels:
    eventing.knative.dev/broker: repro
    eventing.knative.dev/brokerEverything: "true"
  name: repro-kne-trigger
  namespace: default
  ownerReferences:
  - apiVersion: eventing.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Broker
    name: repro
    uid: 80d72fbf-fe7d-43fb-b9c7-01a58ad1c3cf
  resourceVersion: "97973844"
  selfLink: /apis/messaging.knative.dev/v1/namespaces/default/inmemorychannels/repro-kne-trigger
  uid: 5599bb58-8518-4d75-8411-fe3c55be1cb2
spec:
  subscribers:
  - generation: 1
    replyUri: http://broker-ingress.knative-eventing.svc.cluster.local/default/repro
    subscriberUri: http://broker-filter.knative-eventing.svc.cluster.local/triggers/default/default-test-trigger/d29cb073-f5fc-4590-9114-9c05530f548b
    uid: 3b7b418a-c583-4ad1-99c1-a1a72ffd0f8b
status:
  address:
    url: http://repro-kne-trigger-kn-channel.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: Addressable
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: ChannelServiceReady
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: DispatcherReady
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: EndpointsReady
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: ServiceReady
  observedGeneration: 2
  subscribers:
  - observedGeneration: 1
    ready: "True"
    uid: 3b7b418a-c583-4ad1-99c1-a1a72ffd0f8b
vaikas-a01:eventing-camel vaikas$ kubectl delete triggers default-test-trigger
trigger.eventing.knative.dev "default-test-trigger" deleted
vaikas-a01:eventing-camel vaikas$ kubectl get imc repro-kne-trigger -oyaml
apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
metadata:
  annotations:
    eventing.knative.dev/scope: cluster
    messaging.knative.dev/creator: system:serviceaccount:knative-eventing:eventing-controller
    messaging.knative.dev/lastModifier: system:serviceaccount:knative-eventing:eventing-controller
    messaging.knative.dev/subscribable: v1
  creationTimestamp: "2020-09-16T17:46:04Z"
  generation: 3
  labels:
    eventing.knative.dev/broker: repro
    eventing.knative.dev/brokerEverything: "true"
  name: repro-kne-trigger
  namespace: default
  ownerReferences:
  - apiVersion: eventing.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Broker
    name: repro
    uid: 80d72fbf-fe7d-43fb-b9c7-01a58ad1c3cf
  resourceVersion: "97976297"
  selfLink: /apis/messaging.knative.dev/v1/namespaces/default/inmemorychannels/repro-kne-trigger
  uid: 5599bb58-8518-4d75-8411-fe3c55be1cb2
spec: {}
status:
  address:
    url: http://repro-kne-trigger-kn-channel.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: Addressable
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: ChannelServiceReady
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: DispatcherReady
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: EndpointsReady
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-09-16T17:46:04Z"
    status: "True"
    type: ServiceReady
  observedGeneration: 3
```

So, I wonder if something was fixed along the way. When are you planning on ugprading? Also, FYI, there was an issue with some of the releases when going from .16 to .17, but it should have been fixed in the later dot releases. @Harwayne which is the one that has been fixed?

**Comment by MPeyrard86** [comment]
I have put in a request to get our Kubernetes version upgraded, as that is blocking us from upgrading Knative. As soon as that happens, I will be upgrading Knative and trying this again.

**Comment by vaikas** [comment]
ok, thanks and sorry about the trouble :(

**Comment by MPeyrard86** [comment]
No worries. This isn't affecting production or anything. We're using Knative to develop a new feature that hasn't shipped yet.

**Comment by MPeyrard86** [comment]
Quick update: We're _finally_ getting our Kubernetes upgraded to version 1.18. Should happen in the next week or two. I'll be upgrading Knative to 0.18 as soon as that's done and update this bug with the results.

**Comment by pandagodyyy** [comment]
I also met exactly same issue with @mpeyrard .
@mpeyrard  How about now, did you fix it by upgrading?
Actually I met the same problem with IMC channel, knative-eventing 0.18 and 0.19 both.
It seems upgrading cannot help this issue.
@slinkydeveloper @vaikas, I feel it is easy to reproduce it. Because I am just knative beginner and use sample of quick start.  Do we have clue on this issue and how can we walkround it?

**Comment by vaikas** [comment]
@pandagodyyy when you say it's easy to reproduce, if you can reliably reproduce it that would be great? I think both @slinkydeveloper and I tried to repro this and couldn't. I'll try to see if I can do it from .19 today and report back. But in the meantime if you have an easy repro (esp. with IMC) that would be great to share :)

**Comment by pandagodyyy** [comment]
@vaikas, I left message and went to bed yesterday, and when I wakes up today, I found the triggers works as expected. It seem it took several hours for recovering.
So this morning I tried reproduce it in a brand new cluster again, and it happened once more. I recorded it below
Environment: K8s v1.18 ;pre-installed Istio 1.7.3; Knative eventin 1.9

1. kubectl.exe create namespace knative-eventing
2. kubectl.exe label namespace knative-eventing istio-injection=enabled
3. `cat <<EOF | kubectl apply -f -
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "knative-eventing"
spec:
  mtls:
    mode: PERMISSIVE
EOF`
4. kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.19.0/eventing-crds.yaml
5. kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.19.0/eventing-core.yaml
6. kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.19.0/in-memory-channel.yaml
7. kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.19.0/mt-channel-broker.yaml
8. kubectl.exe create namespace premaster
9. kubectl.exe label namespace premaster istio-injection=enabled
10.  `kubectl  apply -f - << EOF
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: premaster
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: test-display
  namespace: premaster
spec:
  broker: default
  filter:
    attributes:
      type: v1
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: hello-display
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-display
  namespace: premaster
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: hello-display
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
---
kind: Service
apiVersion: v1
metadata:
  name: hello-display
  namespace: premaster
spec:
  selector:
    app: hello-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
EOF`

11. kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/sleep/sleep.yaml -n premaster

After all, check knative-eventing 
 
![image](https://user-images.githubusercontent.com/61133973/100967579-7f17be00-356a-11eb-9776-87352630184f.png)

check premster
![image](https://user-images.githubusercontent.com/61133973/100967608-98206f00-356a-11eb-8ddc-5f2dd930d477.png)

Then start sending event to broker, meanwhile monitoring logs of hello-display
 .\kubectl.exe exec -it sleep-64d7d56698-gg8dd -n premaster -- /bin/sh

curl -v "http://broker-ingress.knative-eventing.svc.cluster.local/premaster/default" \
  -X POST \
  -H "Ce-Id: say-hello" \
  -H "Ce-Specversion: 1.0" \
  -H "Ce-Type: v1" \
  -H "Ce-Source: not-sendoff" \
  -H "Content-Type: application/json" \
  -d '{"msg":"Hello World!"}'

Result: message was shown in hello-display

Then I modified trigger with new Type v2
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: test-display
  namespace: premaster
spec:
  broker: default
  filter:
    attributes:
      type: v2
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: hello-display
Sent previous message
curl -v "http://broker-ingress.knative-eventing.svc.cluster.local/premaster/default" \
  -X POST \
  -H "Ce-Id: say-hello" \
  -H "Ce-Specversion: 1.0" \
  -H "Ce-Type: v1" \
  -H "Ce-Source: not-sendoff" \
  -H "Content-Type: application/json" \
  -d '{"msg":"Hello World!"}'

Result: still was shown in hello-display

Send new message with v2
curl -v "http://broker-ingress.knative-eventing.svc.cluster.local/premaster/default" \
  -X POST \
  -H "Ce-Id: say-hello" \
  -H "Ce-Specversion: 1.0" \
  -H "Ce-Type: v2" \
  -H "Ce-Source: not-sendoff" \
  -H "Content-Type: application/json" \
  -d '{"msg":"Hello World!"}'
Result: nothing was shown
(If after several hours, the modified trigger can work)

If I delete current trigger, and then create new one 
After I sent a message, nothing was shown in hello-display
However, check the log by kubectl.exe logs -f mt-broker-filter-79c59cc4dc-spxws -c filter -n knative-eventing
it complained such error
{"level":"info","ts":"2020-12-03T04:28:33.828Z","logger":"mt_broker_filter","caller":"filter/filter_handler.go:170","msg":"Unable to get the Trigger","commit":"0f9a8c5","error":"trigger had a different UID. From ref '13a5a1d0-3201-4283-b251-b4532625298d'. From Kubernetes '6491443d-276e-4448-9227-6fb9c5374984'","triggerRef":"premaster/test-display"}
error: unexpected EOF

**Comment by pandagodyyy** [comment]
I did not enable local cluster gateway (I do not know if it is necessary, event seems can work without local cluster gateway).

**Comment by mpeyrard** [comment]
I have not yet tried with a higher version, because I'm still waiting for my DevOps team to upgrade our version of Kubernetes. I've since noticed that it does not happen 100% of the time. Work-around seems to be to re-install the broker.
