### ISSUE TITLE
Considering removing eventing.knative.dev/scope support in KafkaChannel

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#1524]
Is this used?

**Comment by aliok** [comment]
related: https://github.com/knative/eventing-contrib/issues/1189#issuecomment-624281888

**Comment by aliok** [comment]
Give me some time and let me prepare a Google doc with suggestions for alternatives for this annotation

**Comment by aliok** [comment]
cc @matzew (appreciate your comment here)

**Comment by AceHack** [comment]
I use this
