### ISSUE TITLE
Kafka Channel wont delete

### ISSUE THREAD

**Issue by whitleykeith** [knative/eventing-contrib#1539]
**Describe the bug**
I can't delete the kafka channel due to the following error:

admission webhook "validation.webhook.kafka.messaging.knative.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "subscribable"

 **Expected behavior**
I can delete the channel

 **To Reproduce**
deploy a channel and a subscription to that channel
delete subscription and channel
watch the channel get stuck

 **Knative release version**

v0.16

**Comment by slinkydeveloper** [comment]
Seems like an issue in the api version conversion, @aliok do you know something about it?

**Comment by slinkydeveloper** [comment]
@whitleykeith which kafka channel api version are you using?

**Comment by whitleykeith** [comment]
messaging.knative.dev/v1beta1

**Comment by aliok** [comment]
Looks exactly the same with the comment here: https://github.com/knative/eventing-contrib/pull/1378#issuecomment-658164210

I thought this was only a problem in master and was fixed later before a release.

But, now I realized that I think we need to backport https://github.com/knative/eventing-contrib/pull/1398 to 0.16 branch and make a new 0.16 bugfix release.

**Comment by aliok** [comment]
/assign

I will take the rest of this week off, but I will check this on Monday.

**Comment by aliok** [comment]
@whitleykeith can you give https://github.com/knative/eventing-contrib/pull/1567 a try?

**Comment by aliok** [comment]
@whitleykeith https://github.com/knative/eventing-contrib/releases/tag/v0.16.1 is now released with this fix
