### ISSUE TITLE
HA mode breaks horizontal scaling of kafka channel dispatcher

### ISSUE THREAD

**Issue by AceHack** [knative/eventing-contrib#1556]
**Describe the bug**
In 0.16.x where HA mode was off by default I was able to change the replica count for the kafka channel dispatcher and get horizontal scale.  By this I mean if a topic has 100 partitions and I was to scale to 2 dispatchers I would get 50 partitions owned by dispatcher 1 and 50 partitions owned by dispatcher 2.  If I scaled up to four I would a 25, 25, 25, 25 partition distribution among the dispatchers, etc...  This is the default behavior of the kafka client when there are multiple consumers in a single consumer group.  I was able to achieve incredible throughput numbers using this technique.

As of 0.17.x (I'm on 0.17.1) the default mode is to enable HA.  With HA enabled no matter how many dispatchers are enabled all 100 partitions get assigned to only the leader and the followers get 0.  This completely breaks horizontal scaling and my throughput numbers are terrible now.

 **Expected behavior**
The ability to horizontally scale kafka channel dispatcher by increasing the replica count and relying on the default behavior of evenly distributing kafka partitions among consumers of the same consumer group.

 **To Reproduce**
Install knative eventing 0.17.3
Install knative kakfa channel 0.17.1
Create a kafka channel with more than one partition
Edit the kafka channel dispatcher to have more than one replica

 **Knative release version**
serving 0.17.2, eventing 0.17.3, kafka channel contrib 0.17.1

 **Additional context**
We are able to currently work around the issue by disabling ha on the dispatcher by manually editing the deployment and adding
```
args:
  - "--disable-ha"
```

Also, this PR https://github.com/knative/eventing-contrib/pull/1446 supposedly has a "quick fix" to the problem.  Not sure what that means.  It was called out by @pierDipi in a slack conversation.  It also goes into detail in the comments about what the "real" fix should be, where Leaders are responsible for Reconciles and Both Leaders and followers are responsible for Observables.

**Comment by slinkydeveloper** [comment]
I think this is related to the discussion here https://github.com/knative/eventing-contrib/pull/1446/files#r469492807

**Comment by pierDipi** [comment]
The "quick fix" is what you're doing by disabling HA, but there are some issues with that.
