### ISSUE TITLE
KafkaChannel subscribers list ends up with duplicate subscribers for the same subscription. This results in duplicate dispatches.

### ISSUE THREAD

**Issue by ntzlqx** [knative/eventing-contrib#1560]
**Describe the bug**
Duplicate messages are dispatched to the same knative function

 **Expected behavior**
Events are not duplicated

 **To Reproduce**
I believe the issue occurs upon manual deletion of a subscription, but could be also upon upgrade (not verified)
Another way to replicate: Edit the broker config to add delivery options. This results in recreating all subscriptions and respectively all subscribers are recreated. You will see duplicate subscribers added to the subscribers list of the kafkachannel

 **Knative release version**
0.17.3
 **Additional context**
Editing manually the KafkaChannel subscribers list corrects the issue

**Comment by slinkydeveloper** [comment]
@ntzlqx I tried to remove and create a sub again using a clean 0.17.3 setup, but i don't see any issue. Can you please provide a reproducer code/reproducer script?

Can you post the log (in debug mode) of kafka-ch-controller & kafka-ch-dispatcher when the issue happens?

**Comment by matzew** [comment]
I think https://github.com/knative/eventing/pull/4042  is related here

/cc @pierDipi

**Comment by lionelvillard** [comment]
here more context: https://knative.slack.com/archives/CR2141CGY/p1599849495058400

**Comment by slinkydeveloper** [comment]
@matzew I'm not sure it's related to https://github.com/knative/eventing/pull/4042, it seems more some corner case of the controller logic...

**Comment by slinkydeveloper** [comment]
Is this issue still relevant?

**Comment by ntzlqx** [comment]
I have not tested this...
The issue occurred when editing broker delivery section, I am going to do this today and see if duplicate subscribers appear

**Comment by slinkydeveloper** [comment]
Thanks!

**Comment by ntzlqx** [comment]
Just tested...and did get a duplicate set of subscribers...interestingly not a complete set...
I changed the backoffDelay and backoffPolicy on the broker
All subscriptions got recreated
A new set of subscribers appeared in the kafkaChannel subscribers list (with the new delivery config)
but "stale" subscribers(with the old delivery config) still linger on in the subscribers' list
I suspect this will result in duplicate event delivery as it did when I opened the issue

**Comment by slinkydeveloper** [comment]
Which version are you testing on?

**Comment by ntzlqx** [comment]
0.18

**Comment by ntzlqx** [comment]
I just deleted the stale ones - I have 20 subscribers - 7 remained as duplicates with the old config

**Comment by slinkydeveloper** [comment]
I'm not sure how i can help you without any reproducer, I'm sorry :disappointed:  Can you post the log of the kafka channel controller?

**Comment by ntzlqx** [comment]
Sorry for the delay...I will try to capture the log from the controller now

**Comment by ntzlqx** [comment]
The steps i am following:
1. Edit the the event delivery spec on the broker
2. Check the list of subscribers on the Kafka Channel for duplicates

**Comment by ntzlqx** [comment]
I got 8 duplicate subscribers out of 20 this time

**Comment by ntzlqx** [comment]
[kafkaChController.log](https://github.com/knative/eventing-contrib/files/5532936/kafkaChController.log)

**Comment by slinkydeveloper** [comment]
@devguyio is this related to the status thing you've been working on recently? Can you check it please?

**Comment by devguyio** [comment]
This might get fixed by knative-sandbox/eventing-kafka#182 once it lands.
/assign
/unassign @slinkydeveloper
