### ISSUE TITLE
Adopt apiextension.k8s.io & admissionregistration.k8s.io v1 API

### ISSUE THREAD

**Issue by dprotaso** [knative/eventing-contrib#1599]
The yaml in this repo is still using beta APIs that can switch to v1.

**Comment by dprotaso** [comment]
related: https://github.com/knative/serving/issues/9494

**Comment by dprotaso** [comment]
note: - eventing & serving have switched in previous releases

**Comment by vaikas** [comment]
I just spot checked rabbitmq / natss and they are using both crd v1. rabbitmq is using admissionregistration v1/v1beta1, natss only v1beta1. Wonder if we should create an issue in each repo for these.

**Comment by dprotaso** [comment]
yeah feel free to do whatever - just raising awareness. If you make the separate issues feel free to close this one

**Comment by vaikas** [comment]
/close
This repo is being archived and there's no more code here.
