### ISSUE TITLE
make it easier to see installed Source CRs in a cluster.

### ISSUE THREAD

**Issue by vaikas** [knative/eventing-contrib#176]
## Expected Behavior
it's a bit tricky to see what CRs for sources have been installed. by convention if we just label the created CRs consistently, we'll be able to provide a cleaner user experience.

For example, I can see available sources because I have tagged the CR created like so:

https://github.com/vaikas-google/csr/blob/master/config/cloudschedulersource.yaml#L7

vaikas@penguin:~/projects/go/src/github.com/vaikas-google$ kubectl get crds -l "eventing.knative.dev/source=true"
NAME                                      AGE
cloudschedulersources.sources.aikas.org   50d
gcssources.sources.aikas.org              21h

## Actual Behavior
you have to iterate through all the CRDs to see if they are sources. For example, these all come from the eventing-sources but are not easily discoverable.

vaikas@penguin:~/projects/go/src/github.com/vaikas-google$ kubectl get crds | grep sources.eventing
containersources.sources.eventing.knative.dev         58d
cronjobsources.sources.eventing.knative.dev           7h
gcppubsubsources.sources.eventing.knative.dev         58d
githubsources.sources.eventing.knative.dev            58d
kuberneteseventsources.sources.eventing.knative.dev   58d

## Additional Info
I'm not wedded to the particular label, but sooner we agree on a convention, better off we are.

**Comment by csantanapr** [comment]
What are other alternatives in a k8s to "tag" an object?

I think labels are the most common way to "tag".

annotations serve a different purpose, and putting a field/property feels to invasive.

I like labels as same idioms for "filtering" like affinity/anti-affinity can be use on CRDs in future.

**Comment by matzew** [comment]
Labels seem to work, but feels still a bit weak, no ? 
E.g. I have to ensure it is set... instead of something more _strongly_ typed
