### ISSUE TITLE
Container Source args 

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#18]
the container source `args`:

e.g. in here:
https://github.com/knative/eventing-sources/blob/master/config/samples/sources_v1alpha1_containersources.yaml#L9-L11

can they be populated by ENV_VARs?

**Comment by n3wscott** [comment]
Which is more standard? I think about sources as if you are making a single script and in the context of just a runable, I tend to think about passing command arguments to it vs env_args. But that is just my small view. What is the pros of ENV_VARs?

**Comment by matzew** [comment]
OK, fair point, how about baking weaving in values, that are stored/configed in a `ConfigMap` ? 

I think that would give me some better flexibility

For instance, if I have a source that should pulls an external system every `n` seconds, and send the _result_ to a **Sink**. The desired value may change, and if stored somewhere else (single CM), I feel that reuse of some of the yaml fragments might work better;

e.g. point to a CM versus hardcoded values

**Comment by n3wscott** [comment]
TOTALLY. 

This is still not real code yet... Secrets will be supported too
