### ISSUE TITLE
k8s event source doesn't work on release 0.3.0

### ISSUE THREAD

**Issue by csantanapr** [knative/eventing-contrib#181]
## Expected Behavior
k8s event sample should work on a knative deployment using 0.3.0 release

## Actual Behavior
k8s event source doesn't work, there are error in the logs

## 1. Minikube
for mac Carlo's way 😄 
```
minikube delete
minikube config set kubernetes-version v1.11.6
minikube config set cpus 4
minikube config set memory 8192
minikube config set WantUpdateNotification false
minikube start --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
minikube ssh -- sudo ip link set docker0 promisc on
```
## 2. Install Istio
```
curl -OL https://github.com/knative/serving/releases/download/v0.3.0/istio-crds.yaml
kubectl apply -f istio-crds.yaml

curl -OL https://github.com/knative/serving/releases/download/v0.3.0/istio-lean.yaml
cat istio-lean.yaml | sed 's/LoadBalancer/NodePort/' | kubectl apply --filename -
```
## 3. Install Knative Serving
```
curl -OL https://github.com/knative/serving/releases/download/v0.3.0/serving.yaml
cat serving.yaml | sed 's/LoadBalancer/NodePort/' | kubectl apply --filename -
watch kubectl get pods --namespace knative-serving

curl -OL https://github.com/knative/serving/releases/download/v0.3.0/monitoring.yaml
kubectl apply -f monitoring.yaml
```

## 3. Install Eventing
```
curl -OL https://github.com/knative/eventing/releases/download/v0.3.0/eventing.yaml
kubectl apply -f eventing.yaml
watch kubectl get pods --namespace knative-eventing
```

## 4. Install Event Sources
```
curl -o event-sources.yaml -L https://github.com/knative/eventing-sources/releases/download/v0.3.0/release.yaml
kubectl apply -f event-sources.yaml
watch kubectl get pods --namespace knative-sources
```

## 5. 1 Install Sample App msg dumper
```
curl -o message-dumper-0.3.0.yaml -L \
https://github.com/knative/eventing-sources/releases/download/v0.3.0/message-dumper.yaml
```

### The Channel
```
curl -o kubernetes-event-source-channel.yaml -L \
https://raw.githubusercontent.com/knative/docs/master/eventing/samples/kubernetes-event-source/channel.yaml
kubectl apply -f kubernetes-event-source-channel.yaml
```

### The SA to get permission to events
```
curl -o kubernetes-event-source-serviceaccount.yaml -L \
https://raw.githubusercontent.com/knative/docs/master/eventing/samples/kubernetes-event-source/serviceaccount.yaml\
kubectl apply -f kubernetes-event-source-serviceaccount.yaml
```

### The Event Source
```
curl -o kubernetes-event-source-k8s-events.yaml -L \
https://raw.githubusercontent.com/knative/docs/master/eventing/samples/kubernetes-event-source/k8s-events.yaml
kubectl apply -f kubernetes-event-source-k8s-events.yaml
```

### The Subscription
```
curl -o kubernetes-event-source-subscription.yaml -L \
https://raw.githubusercontent.com/knative/docs/master/eventing/samples/kubernetes-event-source/subscription.yaml
kubectl apply -f kubernetes-event-source-subscription.yaml
```

Test it !
Create a pod
```
kubectl run -i --tty busybox --image=busybox --restart=Never -- sh
```

Delete a pod
```
kubectl delete pod busybox
```

Verify
```
kubectl get pods
kubectl logs -l serving.knative.dev/service=message-dumper -c user-container
```

Here are the logs collected on a 1.11.6 cluster
```
kubectl logs controller-manager-0 -n knative-sources
{"level":"info","ts":1547218967.8800313,"logger":"fallback","caller":"sdk/reconciler.go:52","msg":"Reconciling &TypeMeta{Kind:,APIVersion:,} default/testevents-qx7cn"}
{"level":"warn","ts":1547218967.8907819,"logger":"fallback","caller":"sdk/reconciler.go:74","msg":"Failed to reconcile &TypeMeta{Kind:,APIVersion:,}: sink \"default/testchannel\" (eventing.knative.dev/v1alpha1, Kind=Channel) does not contain address"}
```
in the the eventing controller
```
kubectl logs eventing-controller-847d8cf969-dzwzq -n knative-eventing
{"level":"info","ts":1547218501.9501147,"logger":"kubebuilder.controller","caller":"controller/controller.go:153","msg":"Starting workers","Controller":"subscription-controller","WorkerCount":1}
I0111 15:02:57.075128       1 reconcile.go:51] Reconciling subscription default/testevents-subscription
I0111 15:02:57.075358       1 reconcile.go:87] DeletionTimestamp: <nil>
W0111 15:02:57.089030       1 reconcile.go:230] Failed to fetch SubscriberSpec target &ObjectReference{Kind:Service,Namespace:,Name:message-dumper,UID:,APIVersion:serving.knative.dev/v1alpha1,ResourceVersion:,FieldPath:,}: services.serving.knative.dev "message-dumper" not found
W0111 15:02:57.089100       1 reconcile.go:114] Failed to resolve Subscriber {Ref:&ObjectReference{Kind:Service,Namespace:,Name:message-dumper,UID:,APIVersion:serving.knative.dev/v1alpha1,ResourceVersion:,FieldPath:,} DNSName:<nil>} : services.serving.knative.dev "message-dumper" not found
{"level":"error","ts":1547218977.0960505,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"subscription-controller","Request":"default/testevents-subscription","error":"services.serving.knative.dev \"message-dumper\" not found","stacktrace":"github.com/knative/eventing/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/argent/go/src/github.com/knative/eventing/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/argent/go/src/github.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/argent/go/src/github.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
I0111 15:02:58.096549       1 reconcile.go:51] Reconciling subscription default/testevents-subscription
I0111 15:02:58.097026       1 reconcile.go:87] DeletionTimestamp: <nil>
W0111 15:02:58.101593       1 reconcile.go:114] Failed to resolve Subscriber {Ref:&ObjectReference{Kind:Service,Namespace:,Name:message-dumper,UID:,APIVersion:serving.knative.dev/v1alpha1,ResourceVersion:,FieldPath:,} DNSName:<nil>} : status does not contain address
{"level":"error","ts":1547218978.1018186,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"subscription-controller","Request":"default/testevents-subscription","error":"status does not contain address","stacktrace":"github.com/knative/eventing/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/argent/go/src/github.com/knative/eventing/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/argent/go/src/github.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/argent/go/src/github.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

## Additional Info

**Comment by n3wscott** [comment]
I did the same in a GCP cluster following the documentation and it worked. I do see some of these errors in my logs though

**Comment by grantr** [comment]
sources controller:
- Reconcile attempt 1: Channel exists, but has no address in its Status

eventing controller:
- Reconcile attempt 1: message-dumper Service doesn't exist yet
- Reconcile attempt 2: message-dumper service exists, but has no address in its Status

**Comment by csantanapr** [comment]
I tried again and got better luck but message-dumper never came up, now I'm using release.yaml for eventing

## Install Eventing
```
curl -o eventing-release.yaml -L https://github.com/knative/eventing/releases/download/v0.3.0/release.yaml
kubectl apply -f eventing-release.yaml
watch kubectl get pods --namespace knative-eventing
```

## Install Event Sources
```
curl -o eventing-sources.yaml -L https://github.com/knative/eventing-sources/releases/download/v0.3.0/release.yaml
kubectl apply -f eventing-sources.yaml
watch kubectl get pods --namespace knative-sources
```

I see the in memory provisoner
```
kubectl get pods -n knative-eventing
NAME                                            READY   STATUS    RESTARTS   AGE
eventing-controller-847d8cf969-xq692            1/1     Running   0          20m
in-memory-channel-controller-59dd7cfb5b-846sh   1/1     Running   0          20m
in-memory-channel-dispatcher-67f7497fc-lps7k    1/1     Running   0          20m
webhook-7cfff8d86d-8l747                        1/1     Running   0          20m
```

But I see errors in  `eventing-controller`
```
kubectl logs eventing-controller-847d8cf969-xq692 -n knative-eventing
````
{"level":"info","ts":"2019-01-14T19:58:19.351Z","caller":"logging/config.go:96","msg":"Successfully created the logger.","knative.dev/jsonconfig":"{\n  \"level\": \"info\",\n  \"development\": false,\n  \"outputPaths\": [\"stdout\"],\n  \"errorOutputPaths\": [\"stderr\"],\n  \"encoding\":\"json\",\n  \"encoderConfig\": {\n    \"timeKey\": \"ts\",\n    \"levelKey\": \"level\",\n    \"nameKey\": \"logger\",\n    \"callerKey\": \"caller\",\n    \"messageKey\": \"msg\",\n    \"stacktraceKey\": \"stacktrace\",\n    \"lineEnding\": \"\",\n    \"levelEncoder\": \"\",\n    \"timeEncoder\": \"iso8601\",\n    \"durationEncoder\": \"\",\n    \"callerEncoder\": \"\"\n  }\n}\n"}
{"level":"info","ts":"2019-01-14T19:58:19.351Z","caller":"logging/config.go:97","msg":"Logging level set to info"}
{"level":"info","ts":"2019-01-14T19:58:19.351Z","logger":"controller","caller":"controller/main.go:66","msg":"Starting the Controller","commit":"4712e3a","knative.dev/controller":"controller"}
{"level":"info","ts":"2019-01-14T19:58:19.453Z","logger":"controller","caller":"controller/main.go:99","msg":"Starting metrics listener at %s:9090","commit":"4712e3a","knative.dev/controller":"controller"}
{"level":"info","ts":1547495899.500178,"logger":"kubebuilder.controller","caller":"controller/controller.go:120","msg":"Starting EventSource","Controller":"subscription-controller","Source":{"Type":{"metadata":{"creationTimestamp":null},"spec":{"channel":{}},"status":{"physicalSubscription":{}}}}}
{"level":"info","ts":1547495899.6018233,"logger":"kubebuilder.controller","caller":"controller/controller.go:134","msg":"Starting Controller","Controller":"subscription-controller"}
{"level":"info","ts":1547495899.702933,"logger":"kubebuilder.controller","caller":"controller/controller.go:153","msg":"Starting workers","Controller":"subscription-controller","WorkerCount":1}
I0114 20:06:04.583013       1 reconcile.go:51] Reconciling subscription default/testevents-subscription
I0114 20:06:04.583078       1 reconcile.go:87] DeletionTimestamp: <nil>
W0114 20:06:04.616427       1 reconcile.go:114] Failed to resolve Subscriber {Ref:&ObjectReference{Kind:Service,Namespace:,Name:message-dumper,UID:,APIVersion:serving.knative.dev/v1alpha1,ResourceVersion:,FieldPath:,} DNSName:<nil>} : status does not contain address
{"level":"error","ts":1547496364.665976,"logger":"kubebuilder.controller","caller":"controller/controller.go:209","msg":"Reconciler error","Controller":"subscription-controller","Request":"default/testevents-subscription","error":"status does not contain address","stacktrace":"github.com/knative/eventing/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/argent/go/src/github.com/knative/eventing/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/argent/go/src/github.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\ngithub.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/argent/go/src/github.com/knative/eventing/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/argent/go/src/github.com/knative/eventing/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```
