### ISSUE TITLE
Sources open api spec does not include field descriptions.

### ISSUE THREAD

**Issue by vaikas** [knative/eventing-contrib#182]
## Expected Behavior
when dumping the CRD for a source, I'll get a description for each of the fields.

For example, Cloud Scheduler shows:
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            body:
              description: Optional body to send in the event
              type: string
            googleCloudProject:
              description: Google Cloud Project ID to create the scheduler job in.
              type: string
            httpMethod:
              description: Optional HTTP method to use when delivering the event.
                If omitted, uses POST
              type: string

## Actual Behavior
For example, containersource does not:
 validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            args:
              items:
                type: string
              type: array
            env:
              items:
                type: object
              type: array
            image:
              minLength: 1
              type: string

## Steps to Reproduce the Problem

  1. kubectl get crds containersources.sources.eventing.knative.dev -oyaml
  2. look at the output, fields have no description.
  3.

## Additional Info

**Comment by grantr** [comment]
Our version of controller-tools doesn't generate this, but that was fixed in https://github.com/kubernetes-sigs/controller-tools/pull/111 (and https://github.com/kubernetes-sigs/controller-tools/pull/118). I think if we upgrade we'll get this for free. @n3wscott is working on that; first step is https://github.com/knative/eventing/pull/726.
