### ISSUE TITLE
As a user, I want Google events

### ISSUE THREAD

**Issue by inlined** [knative/eventing-contrib#259]
## Expected Behavior
The open source software Google uses interacts with Google Cloud

## Actual Behavior
Google's events are only routed to Cloud Functions

## Steps to Reproduce the Problem

  1. Read docs

## Additional Info
We should build another event source proxy (this time for *.googleapis.com). We can start by just deploying a Cloud Function that sends our cluster Cloud Events via a webhook. Future features in Google's hosted products can make this a direct connection.

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close
