### ISSUE TITLE
Scaling of Kafka source receive adapters

### ISSUE THREAD

**Issue by bbrowning** [knative/eventing-contrib#274]
## Expected Behavior
The receive adapters for a Kafka source should scale up and down as needed.

## Actual Behavior
Each Kafka source gets a single receive adapter

## Additional Info
For every configured Kafka source, the controller should periodically check the offsets and calculate the lag for each partition in a given topic and consumer group. If the lag is greater than 0, then it scales from 0 to 1. If the lag is 0, it scales to 0. If the lag meets some threshold we'll need to define, it should scale from 1 -> N. That maximum value it should ever scale to is the number of partitions with a lag greater than 0 in that topic.

**Comment by bbrowning** [comment]
This depends on #264 .

**Comment by bbrowning** [comment]
It's unclear at what point we need to scale above 1 receive adapter, since the receive adapter doesn't do much work itself and is really just the thing that passes messages along to the sink. There is undoubtedly a number of topic partitions and message throughput where we need more than 1, but I don't know what that is.

Perhaps as a stop-gap, we should let users manually specify the number of replicas for a KafkaSource? Allowing more than one replica would be useful from a HA standpoint anyway.

**Comment by aslom** [comment]
Do you have a test scenario for it? Should we also have a way to throttle output from receive adapter so it does not start too many events?

**Comment by bbrowning** [comment]
I don't have a specific test for receive adapter scaling yet, although I do have a running system that I'm doing some load tests on using the Kafka source. The receive adapter pod is not yet a bottleneck in my system, but I'm also not testing on a huge cluster.

As far as throttling output from the receive adapter, it will only send one event at a time from each Kafka topic partition. So if you dump 10 million messages into a Kafka topic with only 1 partition, you'll process those messages one at a time. If instead your topic has 100 partitions, you'll process those messages 100 at a time.

**Comment by bbrowning** [comment]
I've successfully been able to autoscale Kafka receive adapters to and from zero by using https://github.com/kedacore/keda - demo video of that at https://vimeo.com/338067366 .

KEDA is still pretty early, but I think an interesting approach would be for the Kafka source to let users opt-in to autoscaling of the receive adapters by additional spec fields in the `KafkaSource` CRD. And, for those fields to take effect, the user would have to bring KEDA.

This would allow us to maintain our current behavior and dependencies while also allow users to experiment with receive adapter autoscaling in Kafka. Longer-term, I expect KEDA will support autoscaling of AWS SQS, GCPPubSub, and other sources that overlap with more than just our Kafka source.
