### ISSUE TITLE
Provider parent object is deep copied twice

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#288]
## Expected Behavior

The object should be deep copied only once

## Actual Behavior

It is copied twice. 

here: https://github.com/knative/eventing-sources/blob/d44413300a25f86f91ef77948478bfb11ec854d9/pkg/controller/sdk/reconciler.go#L54

and here: https://github.com/knative/eventing-sources/blob/d44413300a25f86f91ef77948478bfb11ec854d9/pkg/controller/sdk/reconciler.go#L69

The first copy is correct. The second one is unnecessary as the object is not coming for the cache: `original` is mutating by `r.client.Get( ... )` and has already been deep copied

## Steps to Reproduce the Problem

N/A

**Comment by evankanderson** [comment]
/kind bug

(Prow didn't have that label until just now.)

**Comment by n3wscott** [comment]
It turns out that both of those are not required because controller runtime passes a deepcopy from the client call.

https://github.com/kubernetes-sigs/controller-runtime/blob/abf0c072c7038f95bd88c8770679a98203be3743/pkg/cache/internal/cache_reader.go#L75
