### ISSUE TITLE
Update Kafka source to bulk consume messages

### ISSUE THREAD

**Issue by dubee** [knative/eventing-contrib#292]
Currently the Kafka source consumes one message at a time. This behavior should be changed to support bulk consuming of messages to increase performance. Related comment:
https://github.com/knative/eventing-sources/pull/148#pullrequestreview-212240649.

**Comment by dubee** [comment]
@matzew, FYI.

**Comment by matzew** [comment]
the consumer reads from broker, and it batches those reads. In the code we consume the claim, and messages are consumed from a channel so that is 1-1
