### ISSUE TITLE
Make githubsource's SecretToken optional

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#297]
Right now SecretToken appears to be required:
https://github.com/knative/eventing-sources/blob/master/pkg/apis/sources/v1alpha1/githubsource_types.go#L66

I think it would be nice if it were made optional, and if not provided then the system just created something to use (like a UUID). This value has no meaning outside of this subscription so I don't need the requirement to force the user to specify it. However, if someone does want to do so they can.

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close

**Comment by duglin** [comment]
@n3wscott I think you close this on by mistake - this isn't about gcp

**Comment by lionelvillard** [comment]
move to knative-sandbox/eventing-github: https://github.com/knative-sandbox/eventing-github/issues/36
