### ISSUE TITLE
Add support for a urlPath to Sinks

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#325]
Right now EventSource `Sink`s are of type `corev1.ObjectReference`. This assumes that the sink wants to, and can ,process the incoming event at a URL path of `/`. This may not be ideal for all cases, in particular when the same service supports multiple types of calls/APIs/subscriptions. It would be nice if sinks took an optional `urlPath` type of parameter to allow people to send events to their sink at something other than `/`.

**Comment by akashrv** [comment]
https://github.com/knative/pkg/pull/362#issuecomment-479692177

**Comment by duglin** [comment]
should I move this to the eventing repo?

**Comment by lionelvillard** [comment]
This is supported. See https://github.com/knative/pkg/blob/master/resolver/addressable_resolver.go#L91

**Comment by duglin** [comment]
do we support this via an object ref or just URI?

**Comment by lionelvillard** [comment]
both.

**Comment by duglin** [comment]
cool
