### ISSUE TITLE
gcppubsubsource won't get deleted

### ISSUE THREAD

**Issue by nerusnayleinad** [knative/eventing-contrib#330]
I made a test yesterday with knative eventing (pubsub), which failed, and now I can't delete gcppubsubsource object from my cluster. It is just stuck there.

I tried forcing it, but nothing. I end up deleting the cluster.

**Comment by evankanderson** [comment]
Can you provide the YAML of the GCPPubSubSource object? (Feel free to obscure name/project/secret strings as needed.)

**Comment by meteatamel** [comment]
FYI, I ran into this problem as well with Knative 0.8

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close
