### ISSUE TITLE
Missing containers for some sources

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#331]
## Expected Behavior

images matching the `/cmd` structure on the `knative-nightly`

## Actual Behavior

not matching.

## Steps to Reproduce the Problem

  1. go https://console.cloud.google.com/gcr/images/knative-nightly/GLOBAL/github.com/knative/eventing-sources/cmd?gcrImageListsize=30
  2. go https://github.com/knative/eventing-sources/tree/master/cmd
  3. note that the following are missing

* awssqs_receive_adapter
* heartbeats
* heartbeats_receiver
* websocketsource

## Additional Info

While I see the heartbeasts more of a demo - I wonder why awssqs and especially the websocket are not there ? 

should they be included in the `config` folder ? 

I think the awssqs, might be move to the contrib/ location too ?

**Comment by matzew** [comment]
@n3wscott mind take a look here ?

**Comment by n3wscott** [comment]
> websocketsource

This is in the sample dir, 

See: samples/sources_v1alpha2_websocketsource.yaml

It is not in the release.

**Comment by n3wscott** [comment]
| awssqs_source

Also in the sample dir: https://github.com/knative/eventing-sources/blob/6c13100ca5708a4397b4ec59033b2f6376dbc48d/samples/awssqs_source/README.md

Also not in the release.

**Comment by matzew** [comment]
> See: samples/sources_v1alpha2_websocketsource.yaml

> It is not in the release.

yes. Do you feel we should release the AWSSQS and WEBSOCKET sources?

**Comment by matzew** [comment]
I think the AWSSQS should be moved to `contrib` ...
