### ISSUE TITLE
Allow to set imagePullPolicy for knative sources

### ISSUE THREAD

**Issue by aslom** [knative/eventing-contrib#339]
## Expected Behavior

It should be possible to set imagePullPolicy for receive adapters that are managed by knative sources

## Actual Behavior

Either imagePullPolicy is not set or it is hardcoded

## Steps to Reproduce the Problem

  1. Run any knative source and deploy configuration
  2.Look what is image pull policy if any set in receive adapter
  3.

## Additional Info

There is common pattern with env variable passing image but not iamge pull policy - image is required env variable for example CRONJOB_RA_IMAGE, AWSSQS_RA_IMAGE or GCPPUBSUB_RA_IMAGE: 
https://github.com/knative/eventing-sources/search?q=raImageEnvVar&unscoped_q=raImageEnvVar

imagePullPolicy occasionally used as PullIfNotPresent
https://github.com/knative/eventing-sources/search?q=imagepullpolicy&unscoped_q=imagepullpolicy

I have implemented KAFKA_RA_IMAGE_PULL_POLLICY optional env variable that can be used ot set image pull policy for receive adapter, for example:

```
name: KAFKA_RA_IMAGE_PULL_POLLICY
value: IfNotPresent
```

details:
https://github.com/knative/eventing-sources/pull/303/commits/10551f4a0dc1914461f3fdaf70d246fc18f0eed1

**Comment by aslom** [comment]
This issue came for Kafka source
https://github.com/knative/eventing-sources/pull/303#issuecomment-479523925

**Comment by sebgoa** [comment]
related issue:

https://github.com/knative/eventing/issues/1272

**Comment by vaikas-google** [comment]
Vlosed via:
https://github.com/knative/eventing/pull/1321
