### ISSUE TITLE
Maximum throughput in receive adapters limited by poor HTTP connection handling

### ISSUE THREAD

**Issue by bbrowning** [knative/eventing-contrib#342]
## Expected Behavior

A receive adapter pod should be able to sustain a reasonably high rate of throughput (let's say 1,000 events per second) without throwing errors.

## Actual Behavior

Receive adapter pods start throwing errors after less than a minute of sinking 1,000 events per second.

## Steps to Reproduce the Problem

  1. Create a receive adapter that uses our standard kncloudevents library for sinking events (most or perhaps all of them)
  2. Send 1,000 events per second through that receive adapter - I used Kafka for this test.
  3. After some period of time (the exact amount depending on underlying kernel tuning of the K8s Nodes), you'll start to see errors logged about being unable to open new socket connections.

## Additional Info

Here's an example of the errors that start spewing at a high rate under load:
```
"level":"error","ts":1554325844.1039965,"logger":"fallback","caller":"adapter/adapter.go:87","msg":"Sending event to sink failed: {error 25 0  Post http://sensorstream-raw-service.sensorstream-raw.svc.cluster.local/: dial tcp 172.30.202.124:80: connect: cannot assign requested address}
```

The root of the problem is that Go's net/http only keeps at most 2 connections in its connection pool to a single host by default. A receive adapter sends all events to a single host, so we need to increase that default value to something much higher. Otherwise, we end up with a lot of short-lived TCP connections and eventually get too many in a TIME_WAIT status that things start blowing up.

I've opened https://github.com/cloudevents/sdk-go/issues/98 to track making the proper values configurable in cloudevents/sdk-go.

We'll need to do some testing and decide on a reasonable default to set the tunable values (`MaxIdleConns` and `MaxIdleConnsPerHost`) to so that a single receive pod can achieve high throughput. Ultimately, those values need to approach the maximum concurrency we expect a single receive adapter to be able to sustain. And we should document that expected maximum so a user knows when to scale those receive adapter pods up.

**Comment by n3wscott** [comment]
Set the required values directly in the http client inside the cloudevents sdk http transport object that is given to the cloudevents client.

**Comment by dubee** [comment]
@bbrowning, I've observed the same problem when performance testing the Kafka event source.

**Comment by dubee** [comment]
@n3wscott, @bbrowning, should this issue be open in this repo? Tried to set `MaxIdleConns` and `MaxIdleConnsPerHost` from the event source, but wasn't able to figure it out as the `Transport` struct in `cloudevents` client differs from the `Transport` struct in `net/http`.

**Comment by bbrowning** [comment]
We'll need to update to a newer cloudevents/sdk-go version to be able to pass a custom HTTP client in to the CloudEvents Transport. However, the newer releases exacerbate this issue because they explicitly ask every http client request to close meaning we never get connection reuse. Once we get a fixed release of cloudevents/sdk-go we can fix this properly.

In the meantime, this could be worked around by munging the DefaultTransport, but that feels a bit icky. I have an automated test in-progress for this but I'm a bit iffy about the side-effects of exhausting all socket resources on the test machines in the failure case. However, in the success case, it shouldn't even come close to doing so.

**Comment by bbrowning** [comment]
/assign

cloudevents/sdk-go#110 is the PR to fix this behavior in cloudevents/sdk-go - once that gets merged and released, we can pull in the updated library and add a similar test + fix here so that our `kncloudevents.NewDefaultClient` is configured for this scenario out of the box.

**Comment by dubee** [comment]
Related to CloudEvents update here: https://github.com/knative/eventing-sources/commit/7163c85a1513fee64a42b9d57a300644e92266d2.

**Comment by bbrowning** [comment]
/unassign

Unassigning myself as I haven't had time to run performance tests and verify this fix is still needed. I believe it is, but we need to test before and after to be sure we're fixing it.
