### ISSUE TITLE
Kafka Source: add support for the Kubernetes resources spec,

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#364]
## Expected Behavior

in the `CR` file I am able to set values to _Managing Compute Resources for Containers_, like:

* `resources.limits.cpu`
* `resources.limits.memory`
* `resources.requests.cpu`
* `resources.requests.memory`

which would than delegate to the underlying k8s resources spec, as:

* `spec.containers[].resources.limits.cpu`
* `spec.containers[].resources.limits.memory`
* `spec.containers[].resources.requests.cpu`
* `spec.containers[].resources.requests.memory`

## Actual Behavior

ATM, it is not possible directly in the CR file, that sets up a source.

However, you can already do the "resource limit" settings, but unfortunately not directly on the CR file, you need to edit the existing `deployment` - not hard, but also not super convenient 

Same applies to `livenessProbe` and `readinessProbe`

## Additional Info

As discussed on slack with @evankanderson I am going to prototype this on the KafkaSource and document the steps. so that is can be applied to other supported sources as well

**Comment by matzew** [comment]
Code for Kafka lives here, for instance:

https://github.com/knative/eventing-sources/blob/master/contrib/kafka/pkg/reconciler/resources/receive_adapter.go#L58-L62

**Comment by lberk** [comment]
heh, well, despite the lack of formal prow-bot assignment, I've started looking into this issue! :)
