### ISSUE TITLE
In GcpPubSubSource, map fields to cloud events

### ISSUE THREAD

**Issue by lindydonna** [knative/eventing-contrib#393]
When using `GcpPubSubSource` and the `event-display` service, you get the following payload:

```
Data,
  {
    "ID": "539928682078008",
    "Data": "SGVsbG8gd29ybGQ=",
    "Attributes": null,
    "PublishTime": "2019-05-04T00:09:54.181Z"
  }
```

Note that the data payload is Base64 encoded. A better user experience is for the event source to decode the `Data` field and to map the properties up to the cloud event (where relevant). In principle this could be done in a function framework, but it's better to move this logic up to the event source, so that all consumers can benefit.

**Comment by Harwayne** [comment]
The problem with always decoding is we don't know what should be sent downstream. Is it only a limited number of event types? All event types that are not on a banned list? Does the data of the event need to be validated against a schema to ensure only valid events are being sent? We brought this up in one of the later Type Registry meetings and different partners had different requirements.

@nachocano is working on #398 which I think is our (current) generic answer to this. It allows the GcpPubSubSource to specify a transformer, which is an addressable that takes in the PubSub CloudEvent and responds with a CloudEvent. That response CloudEvent is then sent to the GcpPubSubSource's sink. The transformer can do as much as little validation and modification as it wants, such as extracting the data field into a CloudEvent.

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close
