### ISSUE TITLE
No hardcoded sidecar injecton

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#394]
From @bbrowning:

We shouldn't be hardcoding sidecar injection in our eventing source receive adapters - users need a way to toggle that on/off or we don't add the istio sidecar annotation at all.
Under load I found that we had to disable the sidecar from our kafka receive adapter to get acceptable performance. But that means hand-editing the Deployment after it gets created by the kafka source controller.
because of https://github.com/knative/eventing-sources/blob/7e31c30388380356c0d506920e3da20685802c7c/contrib/kafka/pkg/reconciler/resources/receive_adapter.go#L98

**Comment by akashrv** [comment]
@matzew Are you still working on this?
