### ISSUE TITLE
GcpPubSubSource should support GKE metadata 

### ISSUE THREAD

**Issue by Harwayne** [knative/eventing-contrib#418]
## Expected Behavior

When deploying a `GcpPubSubSource` on GKE, I should be able to omit its `spec.gcpCredsSecret`. At which point the reconciler will use the key exposed by GKE on `http://metadata`.

## Actual Behavior

Failing to specify `spec.gcpCredsSecret` will cause the CO to either be rejected by the Webhook or never become Ready.

## Steps to Reproduce the Problem

  1. Create a GKE cluster with a NodePool that has a ServiceAccount with the PubSub viewer permission granted.
  2. Create a `GcpPubSubSource` that doesn't specify `spec.gcpCredsSecret`.

## Additional Info

This will make it easier to use `GcpPubSubSource` on GKE, removing the necessity of setting up a K8s secret entirely.

Originally requested in slack by @mattmoor.

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close
