### ISSUE TITLE
Move GitHubSource to contrib

### ISSUE THREAD

**Issue by grantr** [knative/eventing-contrib#423]
## Expected Behavior

Sources are organized and installed consistently. GitHubSource, like other sources, lives in `contrib/github` and is installed by applying `github.yaml`.

## Actual Behavior

All sources are in `contrib/<sourcename>` except GitHubSource which is in the root dir. All sources are installed with `<sourcename>.yaml` except GitHubSource which is installed with the inaccurately-named `eventing-sources.yaml`.

/kind chore

**Comment by vincent-pli** [comment]
@grantr 
I think I can help on this task, but I saw the `gitlib source` for `contrib` still pending: #382 , is that any specific reason?

**Comment by grantr** [comment]
Hi @vincent-pli! I'm hoping we'll be able to do more reviews once Kubecon is over this week.

I recommend holding off on this one since there might be some larger structural changes to make at the same time, and we need to consider how to do that.

/cc @n3wscott

**Comment by vincent-pli** [comment]
@grantr Got it, thanks

**Comment by duglin** [comment]
Is someone working on this one?

**Comment by nachocano** [comment]
> Is someone working on this one?

I think there is nobody working on this.
@duglin do you want to go ahead and do it? Or maybe @vincent-pli who expressed some interest?
We should have this in for 0.7. Let me know, otherwise I can work on it. Thanks!

**Comment by nachocano** [comment]
We should wait until this gets merged https://github.com/knative/eventing-contrib/pull/452

**Comment by nachocano** [comment]
ok, will work on this one...
/assign
