### ISSUE TITLE
Move irrelevant samples to eventing or delete them

### ISSUE THREAD

**Issue by grantr** [knative/eventing-contrib#427]
The https://github.com/knative/eventing-sources/tree/master/samples directory contains samples for CronJobSource, ContainerSource, and the heartbeats source (which uses ContainerSource). These sources moved to eventing so the samples should move as well. Or if we don't like these samples anymore, we should delete them.

/cc @n3wscott

**Comment by n3wscott** [comment]
We should move them to docs
