### ISSUE TITLE
Is a Source needed? Is there a way to just send an event?

### ISSUE THREAD

**Issue by ryandawsonuk** [knative/eventing-contrib#453]
I've a situation where a Custom Resource creates a multi-container Deployment (non-knative) and from one of the containers within this I'd like to feed data as a source. There will then be a separate sink implementation.

I am wondering whether I could plug in a URL as an env var to the container so that it could put an event onto a channel directly. Or does the URL only get set on the Source-type resources? Basically I am wondering whether I have to create a Source as an intermediary, so that I send the message first into the Source and then that puts it onto a channel.

Related to https://github.com/knative/eventing-contrib/issues/30, https://github.com/knative/eventing-contrib/issues/343

**Comment by evankanderson** [comment]
You should be able to do this using Broker and Trigger as documented here:

https://knative.dev/docs/eventing/broker-trigger/#manual

We're currently working on a docs refresh; feel free to also send a PR to improve any pages that would help make this more clear.

**Comment by ryandawsonuk** [comment]
Thanks! Have submitted a [PR](https://github.com/knative/docs/pull/1450) to try to help clarify for others.
