### ISSUE TITLE
gcppubsub doesn't install per the install docs

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#455]
When going thru our install docs (e.g. https://github.com/knative/docs/blob/master/docs/install/Knative-custom-install.md ) it includes a pointer to the gcppubsub yaml ( https://github.com/knative/eventing-sources/releases/download/v0.6.0/gcppubsub.yaml ) w/o any other pointers to docs. This would imply that people should be able to `kubectl apply -f https://github.com/knative/eventing-sources/releases/download/v0.6.0/gcppubsub.yaml` and get the controller installed w/o any issues. However, today the controller requires some secrets to be mounted into the pod and so w/o any other actions the controller fails to start.

The install instructions should result in a 100% successful install, so there should be some kind of indication in the install docs that additional steps are needed.

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close
