### ISSUE TITLE
GitHubSource doesn't work with Serving 0.7

### ISSUE THREAD

**Issue by grantr** [knative/eventing-contrib#475]
## Expected Behavior
I can target a Serving 0.7 Service with a GitHubSource.

## Actual Behavior
Doesn't work because Service 0.7 doesn't populate the `status.address.hostname` field.

## Additional Info
Probably an issue for all sources.
See https://knative.slack.com/archives/C9JP909F0/p1561666023287200

**Comment by matzew** [comment]
the kafka source has too,

So,, here:

broken contrig:
https://github.com/knative/eventing-contrib/blob/master/pkg/controller/sinks/sinks.go#L60

vs
eventing:
https://github.com/knative/eventing/blob/master/pkg/duck/sinks.go#L117


looks like this should have been done on contrib too:
https://github.com/knative/eventing/commit/fbee61d9eb61a760a49783196e63a4a0c4c789f0
