### ISSUE TITLE
github event source doesn't pass along original headers

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#537]
## Expected Behavior

I would expect the original github event headers to still be in the message passed to the sink - as appropriate.  In my testing I'm not seeing the `Github-Delivery` and `Github-Event` headers. They do appear as `Ce-Github-...` though.  However, if I have existing code that expects a github event then I shouldn't have to change my code to look for `Ce-Github...` headers.  The conversion to a CloudEvent should augment the event, not remove the github-ness of it w.r.t. headers.

**Comment by lionelvillard** [comment]
move to https://github.com/knative-sandbox/eventing-github/issues/86
