### ISSUE TITLE
Graceful shutdown of subscriptions in GCP PubSub receive adapter

### ISSUE THREAD

**Issue by grantr** [knative/eventing-contrib#54]
The normal usage of `sub.Receive` is to pass it a cancelable context. Then cancel from the outside when appropriate. But because all this program is doing is receiving messages (and we don't have any shutdown logic), there is no reason to call cancel. 

We probably should add graceful shutdown logic, but I would rather do that in the future than in this PR. At worst what will happen is a message will be processed multiple times (i.e. it is sent downstream, but not ACKed, and the RA is shutdown, the new RA sends the same message downstream again).

_Originally posted by @adamharwayne in https://github.com/knative/eventing-sources/pull/39/files#r229334215_

**Comment by n3wscott** [comment]
gcppubsubsource has been removed from this repo. Please see http://github.com/google/knative-gcp 

`PullSubscription` is the replacement. 

/close
