### ISSUE TITLE
[Feature Request] Add Redis as Knative Eventing channels

### ISSUE THREAD

**Issue by MrBokeh** [knative/eventing-contrib#570]
Problem
A lot of existing backend systems uses Redis for caching, it would be good to use Redis as the event channel which is better "out of the box" than the in-memory channel for both development and production.

Persona:
Event consumer

Exit Criteria
Able to use Redis as eventing channels for integration

Time Estimate (optional):
5 days max

Additional context (optional)
The Redis reliable queue RPOPLPUSH seems a reliable way for eventing

**Comment by lionelvillard** [comment]
There is ongoing work in this repo: https://github.com/lionelvillard/eventing-redis

/close
