### ISSUE TITLE
KafkaChannel Dispatcher Refactor

### ISSUE THREAD

**Issue by nachocano** [knative/eventing-contrib#597]
**Problem**
In order to be able to report data plane metrics for the KafkaChannel, we need to refactor it to use the CloudEvents SDK, instead of MessageDispatcher and MessageReceiver. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
The KafkaChannel dispatcher uses the CloudEvents SDK.

**Additional Context:** 
- https://github.com/knative/eventing/issues/1892
- Example from knative-gcp: https://github.com/google/knative-gcp/blob/master/pkg/pubsub/adapter/adapter.go

**Comment by nachocano** [comment]
/assign @matzew  
 
assigning it to you so that you guys have it on your radar

**Comment by nachocano** [comment]
fyi @Harwayne @vaikas-google

**Comment by matzew** [comment]
/assign @matzew  

Thanks @nachocano for the heads up, I put this into our backlog, for next release

**Comment by nachocano** [comment]
@matzew the IMC refactor just got in! along with few other things... See here: https://github.com/knative/eventing/pull/1933
This one can do something similar, and start using the eventReceiver and eventDispatcher.

**Comment by lberk** [comment]
Now that #788 is merged, feel free to close out this issue.

**Comment by Jay-Funk** [comment]
Not sure if this is relevant in this context but since v0.12.2 I experience the behavior that if i sent an event that has **specVersion 0.3** my `kafka-ch-dispatcher` crashed and doesn't recover until i delete the messages in the kafka topic that contain the "wrong" specVersion. Is this behaviour wanted?

**Comment by grantr** [comment]
That seems like a bug to me. We should still be able to deliver specversion 0.3 events. @Jay-Funk can you open an issue? Thanks for reporting!
