### ISSUE TITLE
NatssChannel Dispatcher Refactor

### ISSUE THREAD

**Issue by nachocano** [knative/eventing-contrib#598]
**Problem**
In order to be able to report data plane metrics for the NatssChannel, we need to refactor it to use the CloudEvents SDK, instead of MessageDispatcher and MessageReceiver. 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
The NatssChannel dispatcher uses the CloudEvents SDK.

**Additional Context:** 
- https://github.com/knative/eventing/issues/1892
- Example from knative-gcp: https://github.com/google/knative-gcp/blob/master/pkg/pubsub/adapter/adapter.go

**Comment by nachocano** [comment]
/assign @sayanh 

Sayan I'm assigning it to you so that it's in your radar. I know you've been working on the control plane metrics for natss.

**Comment by nachocano** [comment]
fyi @Harwayne @vaikas-google

**Comment by nachocano** [comment]
@sayanh the IMC refactor just got in! along with few other things... See here: https://github.com/knative/eventing/pull/1933
This one can do something similar, and start using the eventReceiver and eventDispatcher.

**Comment by pierDipi** [comment]
Hi @sayanh, are you working on this issue? 
I would like to submit a PR.
