### ISSUE TITLE
Implement an Eventing source for Prometheus

### ISSUE THREAD

**Issue by syedriko** [knative/eventing-contrib#612]
It would be useful to be able to turn Prometheus alerts and results of PromQL queries into events.

**Comment by matzew** [comment]
With the code written, let's update this https://knative.dev/docs/eventing/samples/writing-a-source/

to get the current steps to what it takes w/ `knative.dev/okg` Controller Runtime.

/cc @lberk

**Comment by aslom** [comment]
Let open issue to track what changes are necessary to make in docs  https://knative.dev/docs/eventing/samples/writing-a-source/ ?

**Comment by lionelvillard** [comment]
related to https://github.com/knative/eventing/issues/2019

This [PR](https://github.com/knative/eventing/pull/2030) is the first step. 

I suggest to first make it easier and then update the documentation.

**Comment by syedriko** [comment]
Here is the initial implementation: https://github.com/knative/eventing-contrib/pull/663
