### ISSUE TITLE
Kafka source docs disappeared?

### ISSUE THREAD

**Issue by aslom** [knative/eventing-contrib#620]
## Expected Behavior

Link to docs (and sample config) should work from 
https://github.com/knative/eventing-contrib/tree/master/kafka/source

## Actual Behavior

Could not find Kafka source docs in 
https://knative.dev/docs/eventing/samples/
or in 
https://knative.dev/docs/eventing/sources/

## Steps to Reproduce the Problem

  1. Open links above

## Additional Info

**Comment by matzew** [comment]
It's here:

https://github.com/knative/docs/pull/1712

**Comment by matzew** [comment]
they are here:  https://knative.dev/development/eventing/samples/kafka/
