### ISSUE TITLE
Flaky e2e tests for Natss?

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#627]
## Expected Behavior

* all runs fine

## Actual Behavior

* does not... on a completely _unrelated_ fix/change, I get:

```
skipped 4974 lines unfold_more
                  "name": "eventing-broker-ingress-token-2phft"
                }
              ]
            }
        tracker.go:128: Waiting for eventing-broker-ingress to be deleted
--- FAIL: TestChannelClusterDefaulter (270.60s)
    --- FAIL: TestChannelClusterDefaulter/TestChannelClusterDefaulter-NatssChannel (270.60s)
        test_runner.go:81: namespace is : "test-channel-cluster-defaulter-natss-channel-5k9m7"
        tracker.go:144: Waiting for all KResources to become ready
        channel_defaulter_test_helper.go:113: The defaultchannel is expected to create 1 underlying channel, but got 0
        tracker.go:123: Cleaning resource: "e2e-defaulter-subscription"
            {
skipped 256 lines unfold_more
                  }
                ]
              }
            }
        tracker.go:128: Waiting for e2e-defaulter-channel to be deleted
FAIL
FAIL	knative.dev/eventing-contrib/test/e2e	270.880s
```

/cc @Fredy-Z

**Comment by Fredy-Z** [comment]
I tried to fix the flaky test in https://github.com/knative/eventing/pull/1885, but clearly I failed.

The reason is because I misunderstood the meaning of resync time. I thought 0 meant resynchronize as soon as possible, but it's actually the opposite. See the doc in https://godoc.org/k8s.io/client-go/tools/cache#NewInformer:
```
resyncPeriod: if non-zero, will re-list this often (you will get OnUpdate
  calls, even if nothing changed). Otherwise, re-list will be delayed as
  long as possible (until the upstream source closes the watch or times out,
  or you stop the controller).
```

I haven't figured out what can be a better way to fix it...

**Comment by nachocano** [comment]
This might have to do with the refactor of event_dispatcher and event_receiver in eventing... The e2e seems to use the latest HEAD, and there might be a problem there...
In an unrelated change, I also have the same problem... https://github.com/knative/eventing-contrib/pull/631
