### ISSUE TITLE
Sources require eventing

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#653]
Tried to run just the kafka source (with serving), so that I just connect my kafka events to `ksvc` services. without anything else from eventing

## Expected Behavior

* sources can run independently from eventing

## Actual Behavior

API type requirement, like:

```
E1016 10:15:20.928292       1 reflector.go:125] knative.dev/pkg/controller/controller.go:437: Failed to list *v1alpha1.EventType: the server could not find the requested resource (get eventtypes.eventing.knative.dev)
```

## Steps to Reproduce the Problem

  1. deploy the kafka-source yaml and see the `kafka-controller-manager` to come up
  2. apply a `KafkaSource` CR file, and get the error from above

**Comment by matzew** [comment]
> It is supported for CronJob and APIServer sources.

I don't see them offered as individual bags of yaml

**Comment by lionelvillard** [comment]
I was replying to "It would be also great to be able to run it without serving"

**Comment by lionelvillard** [comment]
I agree with the requirements and removing the hard dependency on eventing. 

I can easily see how sources could work without `EventType`. Do you think we also need to remove any mention of `EventType` in the source status conditions?

**Comment by aslom** [comment]
Could we make it optional?

**Comment by aslom** [comment]
I can confirm I got the same problem and it was fixed by applying the EventType CRD file

before endless stream of 

```
E1021 20:29:13.609292       1 reflector.go:125] knative.dev/pkg/controller/controller.go:437: Failed to list *v1alpha1.EventType: the server could not find the requested resource (get eventtypes.eventing.knative.dev)
```

after using eventing operator

```
$ k -n knative-sources logs kafka-controller-manager-0
2019/10/21 20:30:03 Registering Components.
2019/10/21 20:30:03 Setting up Controller.
2019/10/21 20:30:03 Adding the Apache Kafka Source controller.
2019/10/21 20:30:03 Starting Apache Kafka controller.
```
