### ISSUE TITLE
Source API version promotion

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#654]
While there are a large number of different sources (and channels) in the `eventing-contrib` repo, I was wondering how the team generally feels about promoting some components to `v1beta1` ?

There are components that have a fairly stable API, such as
* Github Source
* Apache Kafka Source
* Apache Camel-K Source

Generally each source is pretty independent from the other, so there is IMO no real problem in moving some _stable_ components to a new API Level.

I am interested and wondering what would the process be to bump some components to the next level? 

>NOTE: I know that we continue to add new sources (E.g. Apache CouchDB Source), and those new sources are for sure starting with `v1alpha1`

**Comment by matzew** [comment]
As for a bar to promote them, some thoughts that @lionelvillard and I had

* API/CRD stable: no breaking changes for some time* (tbd)
* Make sure proper usage of CloudEvent and perhaps require a "min" usage of 0.2+ ?
* some reasonable amout of tests in the source

Generally they are very independent units (see #653)

**Comment by aslom** [comment]
@matzew what about improving Kafka source configuraiton consistency that may change API? https://github.com/knative/eventing-contrib/issues/655

**Comment by matzew** [comment]
@aslom what will change on the channel API ?

**Comment by aslom** [comment]
add more configurable parameters to kafka channel CRD?

**Comment by evankanderson** [comment]
My $0.02 is that it would be premature to promote a source interface to `v1beta1` if the eventing core may change the duck type expectations for the Source or Channel types.

@vaikas-google and @akashrv input would be very helpful here for a commitment on the stability of these interfaces.

**Comment by vaikas-google** [comment]
Oops, sorry, this fell totally through the cracks. Yes, I think we should not move the sources ahead of the core types. Let's discuss this in conjunction with moving the core APIs to v1beta1 and revisit this after that?
