### ISSUE TITLE
[BUG] Missing support for event processing retries

### ISSUE THREAD

**Issue by atamon** [knative/eventing-contrib#656]
**Describe the bug**
Using  KafkaChannel, when my Adressable pod fails to process the message, either responding with a non 2XX or not at all to the HTTP request, the message is lost forever.

 **Expected behavior**
I would expect my pods to receive the event over and over until I have properly acknowledged that the message has been properly processed by my application. If there are multiple pods receiving these events, I would expect some kind of round-robin behavior.

 **To Reproduce**
* Set up knative eventing using a KafkaChannel broker
* Produce a message to a channel
* Set up an Adressable to receive events from the channel
* Make sure the adressable doesn't respond to the incoming HTTP request, or
* Answer status=500

 **Knative release version**
0.6.1

 **Additional context**
I come from a kafka background where they've taken quite some consideration in this issue, making sure that no messages are lost due to consumers failing. I found this TODO noted: https://github.com/knative/eventing/blame/ab2600952f58339a0c8f673a712c4acdd5912757/contrib/kafka/pkg/dispatcher/dispatcher.go#L296.

It would be great to know what kind of future plans you had for this.

Thanks for building an awesome platform!

**Comment by pierDipi** [comment]
This is done.
/close
