### ISSUE TITLE
Operators for Sources

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#658]
How do people feel that we offer operators for (stable) sources?

I did hack together this https://github.com/matzew/kafka-source-operator

and it just installs the `KafkaSource` - that's all I really needed 

It works fine with k8s `services` and `ksvc` as its sink. But no requirement on Eventing itself

**Comment by matzew** [comment]
See #653 and #654

**Comment by aslom** [comment]
I use dit and it worked in my cluster that had only knative kafka source (not other knative artifacts installed)

```
Events:
  Type    Reason     Age   From                   Message
  ----    ------     ----  ----                   -------
  Normal  Scheduled  55s   default-scheduler      Successfully assigned default/knative-eventing-operator-66fcc55f9b-ffjvr to 10.220.100.5
  Normal  Pulling    54s   kubelet, 10.220.100.5  Pulling image "docker.io/matzew/kafka-source-operator:latest"
  Normal  Pulled     51s   kubelet, 10.220.100.5  Successfully pulled image "docker.io/matzew/kafka-source-operator:latest"
  Normal  Created    51s   kubelet, 10.220.100.5  Created container knative-eventing-operator
  Normal  Started    51s   kubelet, 10.220.100.5  Started container knative-eventing-operator
```

**Comment by aslom** [comment]
To make testing easier without requiring installing knative use hello-display instead of event-display? 
Replace/add to README setup (remove --namespace event-example or use it in kafka source beside changing event-display): https://knative.dev/development/eventing/getting-started/#creating-event-consumers

**Comment by aslom** [comment]
also replace  `image: docker.io/matzew/kafka-source-operator:latest` with 
`knative.dev/eventing-operator/cmd/manager` and ko apply is used?

**Comment by aslom** [comment]
https://github.com/matzew/kafka-source-operator/pull/5

**Comment by lionelvillard** [comment]
@matzew as a starting point that'd be nice to have some documentation about the process of creating an operator for sources. Then hopefully we can work on fully automating this process.
