### ISSUE TITLE
Add Kafka Sink

### ISSUE THREAD

**Issue by aslom** [knative/eventing-contrib#682]
## Expected Behavior

Allow Knative sink to send events to Kafka - symmetrical to Kafka source

## Actual Behavior

Not possible with code in Knative eventing

## Steps to Reproduce the Problem

  1. Use event-display as sink to print events

## Additional Info

Based on comments @jamesward

**Comment by jamesward** [comment]
Thanks!  Sorry I didn't file this.

**Comment by n3wscott** [comment]
There is nothing special about a sink aside from being `addressable`. 

For example, in google/knative-gcp, it models pubsub. I created a PullSubscription backed by a deployment, and also created a Topic backed by a ksvc. A channel combines both into do what we think of the thing we want channels to do. But the components are independently useful. 

`PullSubscription` adheres to the `Source` contract, and `Topic` adheres to the `Addressable` contract. 

This is not a good first issue as it is open ended and unclear what should be produced. 

/remove-good-first-issue

**Comment by aslom** [comment]
@n3wscott interesting - can I deploy only Topic component as a knative sink for gcp pubsub? Where can I find an example of it? My thinking for good first issue was that functionality is very simple could be run just with command line arguments without need to use CR.

**Comment by aslom** [comment]
I wrote my own in Python as I needed it for testing - maybe I add and we refactor it as needed? I think there is real need for it ...

**Comment by aslom** [comment]
First version is in PR https://github.com/knative/eventing-contrib/pull/1406

It is fully working Kafka Sink that can be deployed in k8s cluster.

Next steps are to add security, unit tests (not sure how to mock sending to Kafka topic?), create KafkaSink CR and add controller reconciliation support for it

**Comment by slinkydeveloper** [comment]
Done in https://github.com/knative-sandbox/eventing-kafka-broker/pull/134
