### ISSUE TITLE
kafkasource could mark specifed bootstrapserver URI correct/incorrect in status

### ISSUE THREAD

**Issue by lberk** [knative/eventing-contrib#691]
## Expected Behavior
It would be nice to mark the `kafkasource.bootstrapServer` URI as correct/addressable or incorrect in the status field to easily diagnose a necessary parameter is correct or incorrect.

## Actual Behavior
We've had cases where an incorrect `bootstrapserver` URI leads to a crashloopbackoff without any clear reason as to why (and the status updates would appear to indicate everything should be working properly).  Considering it is a required & configurable field in order for the `kafkaSource` to work, it might be worth considering making it more obvious if it incorrect.

## Steps to Reproduce the Problem
  1. Define a kafkasource w/ incorrect `bootstrapserver` spec
  2. `kubetctl get kafkasource kafka-source-[...] -oyaml`
  3. Observe an 'all clear' status & conditions with the kafkasource crashloopbackoff'ing

## Additional Info

**Comment by aslom** [comment]
Incorrect means URI points to broker that is down or connection is blocked?

**Comment by lberk** [comment]
Or is just a plain old typo

**Comment by aslom** [comment]
Dao you mean typo in hostname so it does not resolve?

**Comment by aslom** [comment]
Maybe that should be actually checked by kafka source controller before source is created? And then error recorded in CR?
