### ISSUE TITLE
Camel Source usage of Desitination

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#694]
The Camel Source should adpot `Destination` type, https://docs.google.com/document/d/1EAf9NLwDX3c9DS8lr6KxjtgRXUmkFGIcG6DeAYd5UHI/edit#

**Comment by nicolaferraro** [comment]
Thanks @matzew. Is this needed for 0.10.x?

**Comment by matzew** [comment]
yeah, would be good, I guess to PR against the branch for a 0.10.x release?  Or we do just the master update for 0.11.0 ?

I mean the core sources, and in contrib the kafka and couchdb have it already in 0.10.
