### ISSUE TITLE
Kafka should retry sending events

### ISSUE THREAD

**Issue by lionelvillard** [knative/eventing-contrib#753]
## Expected Behavior
Kafka channel should retry sending events when they failed to be consumed by Kafka consumers.

## Actual Behavior
No retry

See https://github.com/knative/eventing/tree/master/docs/delivery

**Comment by pierDipi** [comment]
@lionelvillard Does https://github.com/knative/eventing-contrib/pull/1114 solve/relate to your issue?

**Comment by lionelvillard** [comment]
it's a good start! We started to support retries at the CloudEvent SDK level. See https://github.com/cloudevents/sdk-go/commit/abe312410b9835bd8317f9304868d9e7546ed2be.
