### ISSUE TITLE
Make it easier to run the e2e tests

### ISSUE THREAD

**Issue by duglin** [knative/eventing-contrib#756]
In https://github.com/knative/eventing-contrib/blob/master/test/README.md
it says we can run the integration tests via the presubmit-tests.sh script, but it says:
- - -
Note that if the tests you are running include integration tests, it will create a new GKE cluster in project $PROJECT_ID, start Knative Serving and Eventing system, upload test images to $KO_DOCKER_REPO, and run all e2e-*tests.sh scripts under test. After the tests finish, it will delete the cluster.
- - -
Many people don't use GKE so it would be great if the test scripts just ran the tests and assumed the person already setup kube, knserving, kneventing, kneventing-contrib then it can be run by anyone on any cluster.

Side note - I can't figure out how to upload the test images since the docs don't mention a required param to the script and I'm not sure what the arg is supposed to be `test/test_images` doesn't seem to work

**Comment by slinkydeveloper** [comment]
If you have a running minikube on your local machine and `$KO_DOCKER_REPO` configured, you won't need any GKE, gcloud or similar google cloud tools. You just need:

```shell
test/e2e-tests.sh --run-tests
```

Test images are uploaded by the `e2e-tests.sh` script too using ko. To upload a test image, you need to add a pod.yaml like [this one](https://github.com/knative/eventing/blob/master/test/test_images/logevents/pod.yaml) in the root of the test image dir

**Comment by duglin** [comment]
@slinkydeveloper it appears that `test/e2e-tests.sh --run-tests` will also try to do things like install eventing. Is there a way to just run the tests w/o it doing any additional setup at all?

**Comment by slinkydeveloper** [comment]
When I don't need the setup/tear down i just use go test:

```
go test -v -tags=e2e -count=1 ./test/e2e -tag e2e
```
