### ISSUE TITLE
Share code between Kafka Source and Channel

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#770]
## Expected Behavior

code shared between source and channel for kafka

## Actual Behavior

It's not really the case. both are fairly indepdent implementations. a bit of consumer code is shared, but we could have done better there.

## Additional Info

Design document, including a CloudEvents binding for kafka:

https://docs.google.com/document/d/1ve1pAfs1uPRQVi8VxrUbpchrbSf7S3N2_seoIU9XBx4/edit#

**Comment by matzew** [comment]
related #682

**Comment by pierDipi** [comment]
The proposal is almost what we're doing in https://github.com/knative-sandbox/eventing-kafka-broker

@slinkydeveloper, can we close this?

**Comment by slinkydeveloper** [comment]
This issue is invalid
