### ISSUE TITLE
Github Source not CloudEvent 1.0 compliant

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#780]
## Expected Behavior

all is good

## Actual Behavior

Source uses delivery header names as attribute names on the _extension_, but those are like `X-GitHub-Event` (see https://developer.github.com/webhooks/#delivery-headers), where we are bound to CE [spec](https://github.com/cloudevents/spec/blob/v1.0/spec.md#attribute-naming-convention):

> CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.

## Proposal 

actually nuke the X and the `-`, and just use `event` and `delivery` instead ...

**Comment by matzew** [comment]
drafted some PR for this:  https://github.com/knative/eventing-contrib/pull/781

**Comment by aslom** [comment]
@duglin I think that is covered by https://github.com/cloudevents/spec/blob/master/adapters/github.md except for X-Hub-Signature?

**Comment by duglin** [comment]
Correct, if you want certain http headers to be picked up as CE extensions then you'll need to adhere to the CE rules. Which includes the `ce-` prefix and the subset of allowable chars.

**Comment by matzew** [comment]
Subject and type already cover those two GH events. So we are good here

/close
