### ISSUE TITLE
Kafka Channel cloudevents client should use eventing's good_client

### ISSUE THREAD

**Issue by lberk** [knative/eventing-contrib#796]
## Expected Behavior
Kafka's dispatcher should take advantage of the tuning done in eventing's `good_client` where possible as noted by @nachocano 
https://github.com/knative/eventing-contrib/pull/788#discussion_r356243909
## Actual Behavior
Currently kafka's dispatcher uses the default `NewDefaultClient()`

**Comment by lberk** [comment]
/assign @lberk 
WIP: https://github.com/lberk/eventing-contrib/tree/good_client
will benchmark before and after the changes to see if there's any improvement, PR once measurements established

**Comment by grantr** [comment]
/kind good-first-issue

Still working on this one @lberk?

**Comment by lberk** [comment]
@Grantr the branch linked has a working implementation. I just wanted to benchmark it with Mako before I committed the values blindly.  I’ll get to setting up Mako and testing this week
