### ISSUE TITLE
GitHubSource does not update the webhook if the ksvc external url changes.

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-contrib#828]
## Expected Behavior

If I delete the ksvc that backs the GitHubSource, it should make a new ksvc and modify the registration in github.com to point to this new service.

## Actual Behavior
The registration does not appear to be modified, but the ksvc is recreated. This results in the gen-name of the ksvc to be different than the registration and webhooks start failing. 

## Options

1. Update the github webhook registration if the external url of the ksvc changes. 
1. Do not generate a random name for the ksvc.
    - There is still an issue if I add or edit the custom domain of the cluster, the config will have to be updated in github.

## Steps to Reproduce the Problem

  1. Make a GitHubSource
  1. Delete the ksvc that backs it manually.
  1. See that a new ksvc is created but with a new gen name and is now out of sync with github.com.

## Additional Info

**Comment by aliok** [comment]
@tom24d  Did you have a similar problem in DockerHubSource?

**Comment by tom24d** [comment]
I have confirmed this was already fixed by #1021 with option 1.

/close
