### ISSUE TITLE
Kafka event source doesn't work for key types other than String

### ISSUE THREAD

**Issue by gunnarmorling** [knative/eventing-contrib#841]
## Expected Behavior
Kafka messages with a key type such as `Integer` or `Long` should be supported.

## Actual Behavior
Using another key type than String will cause the source to fail (see `string(key)` call in _adapter.go_).

## Steps to Reproduce the Problem

  1. Send me Kafka message with a key type that's not a string
  2. Launch the Kafka event source based on that topic
  3.

## Additional Info
-

// CC @matzew

**Comment by matzew** [comment]
actual error message is

```
{"level":"error","ts":"2020-01-22T09:57:04.528Z","logger":"kafkasource","caller":"adapter/adapter.go:152","msg":"An error has occurred while consuming messages occurred: ","error":"Post http://source-display.default.svc.cluster.local: net/http: invalid header field value \"\\x00\\x00\\x00\\a\" for key Ce-Key","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start.func3\n\t/home/matzew/go/src/knative.dev/eventing-contrib/kafka/source/pkg/adapter/adapter.go:152"}
```

commenting out https://github.com/knative/eventing-contrib/blob/master/kafka/source/pkg/adapter/adapter.go#L186 "fixes" the issue

**Comment by gunnarmorling** [comment]
I think you'd need to have some sort of deserializer concept, which allows to plugin specific key deserializers, similar to e.g. the Kafka console consumer, where they can be specified upon invocation: `key.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer`.

**Comment by slinkydeveloper** [comment]
Unfortunately @gunnarmorling sarama doesn't have such feature. Or we provide it from kafka source side, or we just encode the key as base64 to be sure it doesn't throw any failure

**Comment by gunnarmorling** [comment]
I see; yeah, so would be nice to have at least support for the most common types such as string, integer, long before falling back to base64 encoding.
