### ISSUE TITLE
kafka consumer_factory consumerGroup.Consume connection errors are ignored 

### ISSUE THREAD

**Issue by maschmid** [knative/eventing-contrib#851]
https://github.com/knative/eventing-contrib/blob/86bac88600f79123e3e29babc33a44007c6ff419/kafka/common/pkg/kafka/consumer_factory.go#L80-L81

consumerGroup.Consume errors are ignored.

While the comment "// If any error, they are reported in error channel, so we can skip this message" suggests it is not needed, it is not exactly true, as it may return connection errors even before the error channel is setup. 

We should assume that if consumerGroup.Consume returns an error, it didn't start the consumer group properly (and perhaps retry?)

**Comment by slinkydeveloper** [comment]
`consumerGroup.Consume` is blocking until the consumer session is closed, so i think it makes sense to send the error back to consumer handler errors channel
