### ISSUE TITLE
[CamelSource] Migrate to sources.knative.dev api group

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-contrib#867]
## Expected Behavior
The resource is inside of the api group `sources.knative.dev`

## Actual Behavior
`sources.eventing.knative.dev`

there are no owners for this in https://github.com/knative/eventing-contrib/blob/master/OWNERS_ALIASES

**Comment by matzew** [comment]
I've pinged the Camel guys, @n3wscott

**Comment by nicolaferraro** [comment]
I'm taking this!
