### ISSUE TITLE
[ceph] Migrate ceph impl to SinkBinding

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-contrib#868]
`ContainerSource` is deprecated, `SinkBinding` is the new way to add the source contract to a PodSpecable. 

`ContainerSource` will be removed in `0.14`

/assign yuvalif

**Comment by tom24d** [comment]
In favor of #1255, this also needs to be done. 

The doc to follow: https://github.com/knative/docs/blob/master/docs/eventing/migration/sinkbinding.md
The replacement also contains the update of `Channel` and `Subscription` `v1alpha1` to `v1beta1` in the samples.

/assign tom24d
