### ISSUE TITLE
Document Channels in eventing-contrib

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#895]
From @mattmoor :

Context: I've been trying to consolidate our install docs, and something that popped out of that is trying to incorporate the stuff documented here, which includes a random subset of sources: https://knative.dev/docs/install/knative-custom-install/

Ask: Here's what I'd like to see for every source that lives in Knative in some capacity:

1. a regular release with install instructions
2. a sample that we can link from the install block (bonus: tests!)
3. for everything not satisfying the above: a feature track project board, which clearly calls out who owns it and what work is left.

/assign

**Comment by matzew** [comment]
The project has two channel implementations,

[] **NATSS:** A little bit of info in [here](https://github.com/knative/eventing-contrib/tree/master/natss/config). But could be improved. @Abd4llA any means to update this?
[] **Apache Kafka:**  Documentation and install instructions are [here](https://knative.dev/docs/eventing/samples/kafka/channel/index.html).

**Comment by matzew** [comment]
For Kafka we added it to the `knative-with-any-k8s.md `:  https://github.com/knative/docs/pull/2200

**Comment by matzew** [comment]
NATS PR -> https://github.com/knative/docs/pull/2200

**Comment by vaikas** [comment]
The original ask quoted was for sources, I think we should have both tracked, one for channels and one for sources.

**Comment by matzew** [comment]
Sources are here, @vaikas   https://github.com/knative/eventing-contrib/issues/894

**Comment by vaikas** [comment]
sorry :) the quote pasted to the issue definition talks about sources :)

**Comment by mattmoor** [comment]
I think I cross-posted the same thing to channels as a "We should do this for channels too" so probably my bad :)

**Comment by matzew** [comment]
Last missing piece is https://github.com/knative/docs/pull/2214  from @nachocano 

@nachocano once your PR merges, can you close this ?

**Comment by nachocano** [comment]
> Last missing piece is [knative/docs#2214](https://github.com/knative/docs/pull/2214) from @nachocano
> 
> @nachocano once your PR merges, can you close this ?

Sure!
