### ISSUE TITLE
Kafka channel loses broker TTL header

### ISSUE THREAD

**Issue by vaikas** [knative/eventing-contrib#904]
## Expected Behavior
Using kafka channel out of the box should work with Broker

## Actual Behavior
It does not because it drops the TTL extension header as witnessed by the logs:
{"level":"warn","ts":"2020-02-11T11:48:00.158Z","logger":"broker_filter","caller":"filter/filter_handler.go:190","msg":"No TTL seen, dropping","commit":"b6f2702","triggerRef":"kafka-broker/display-trigger","event":"Validation: valid\nContext Attributes,\n  specversion: 1.0\n  type: dev.knative.cronjob.event\n  source: /apis/v1/namespaces/kafka-broker/cronjobsources/test-cronjob-source\n  id: 64877a8e-cf41-47fe-89a9-73d6bb94c1ff\n  time: 2020-02-11T11:48:00Z\n  datacontenttype: application/json\nData,\n  {\n    \"message\": \"Hello world!\"\n  }\n"}

## Steps to Reproduce the Problem

  1. Create a broker that uses kafka channels as per our installation documents
  2. Create a cronjob source that sends events to it and create a trigger that sends events to event display ksvc
  3. events don't show up, and the filter-dispatcher has the log message above.

## Additional Info

**Comment by ajp-lqx** [comment]
Ran into this issue today and found these PRs. Was able to pull the latest master, build the kafka channel dispatcher, write a quick Dockerfile, and replace the image for my kafka-ch-dispatcher as a quick-fix for now, but was curious on what schedule are patch releases made? Additionally, I was not able to find a Dockerfile for anything in eventing-contrib, is this on purpose or am I simply not seeing knative's CI files?

**Comment by vaikas** [comment]
First of all, great to hear it fixed the issue 💪 
eventing-contrib has the releases here, we do not release Dockerfiles, but Images. We'll try to see about getting a patch release out today including these fixes.

**Comment by vaikas** [comment]
aaaand, by here, I mean here: 😄 
https://github.com/knative/eventing-contrib/releases

**Comment by ajp-lqx** [comment]
Sounds good thank you :)
