### ISSUE TITLE
Make Kafka consumer group information or Trigger names or Trigger labels available to sinks on event delivery

### ISSUE THREAD

**Issue by FWiesner** [knative/eventing-contrib#909]
## Expected Behavior
Subscriptions to KafkaChannels via Triggers map to different consumer groups on the underlying topic. To implement custom message forwarders that can deal with different external endpoints, it would be required to get a reference from the consumer group to the entity describing the external endpoint. In the most simple solution, the KafkaChannel could therefore allow stamping each delivered message with the consumer group name. Users might want to turn this on and off, based on whether they want to have multiple similar Triggers, that link the same Broker to the same KSVC with the same selection of events.

A more general solution that would expand beyond Kafka would be that messages that get delivered would optionally be stamped with the name of the Trigger of origin.

## Actual Behavior
Kafka consumer group information not shared with the message sink that gets called

## Steps to Reproduce the Problem

  1. create a Broker with a KafkaChannel and a sink application
  2. deploy two differently named Triggers with the same configuration subscribing the sink application with the Broker
  3. send an event into the broker
  4. the message is delivered two times, but with exactly same headers and payload

## Additional Info

**Comment by matzew** [comment]
@FWiesner can you please update info's on the use-case here? 

Not sure if the proposed feature would less or more leak internals of the implementation to the outbound consumers.

**Comment by FWiesner** [comment]
Hi @matzew,

think of this use case:
- you have one type of event with low to medium occurrence rate
- your listeners are unreliable and could be individually offline for maintenance over whole weekends
- you therefore want different consumer groups for each listener because of independent delivery/retries --> different Triggers, ~7 days message TTL
- here the message sink that Knative Eventing sends the event to is generically able to handle all external listeners and communicates with them via a proprietary (in our case and industry standard) API. For external endpoints to connect to, just different config lookup keys are needed.
- you therefore can deal with the situation in two ways:
  1. you register a sink KSVC for each external listener, just with different env settings to seed the external URL information or at least the configuration lookup keys
  2. you use one and the same KSVC for every external listener and make sure the events carry enough information to identify for which external listener the particular event delivery is meant
- approach 1 does not need a change to Knative, but causes a lot of pain in case your forwarder services are expensive to run and/or have to be spawned more than a few times. Think of a situation where you have to run a Spring Boot service or even just a Microprofile service with a JVM and you have 30 external listeners. Yes, spawning 30 pods at once is possible, but certainly not desirable, if one or two pods could handle the complete load of the delivery of the sole event to the 30 listeners (as 30 individual CloudEvents)

**Comment by FWiesner** [comment]
the most generic solution I could think about here, which doesn't leak internal information of the KafkaChannel, would be that the Triggers that get registered, could carry a label that would be stamped on every message delivered for the Trigger. Then information about the consumer group is not needed

**Comment by FWiesner** [comment]
@matzew just thought I should perhaps add a few diagrams.

Current Solution with existing trigger approach
```
                     /-> Trigger 1 -> Transformation and publishing to external URL 1
Source -> Broker [with KafkaChannel]
                     \-> Trigger 2 -> Transformation and publishing to external URL 2
```

Proposed Approach
```
                     /-> Trigger 1 [enriches message with ce_delivered_by="Trigger 1"] \
Source -> Broker [with KafkaChannel]                                                    => Transformation and publishing to URL looked up by ce_delivered_by
                     \-> Trigger 2 [enriches message with ce_delivered_by="Trigger 2"] /
```

Btw could this issue be moved to knative/eventing perhaps?
