### ISSUE TITLE
Migrate kafka source controller to use generated reconciler

### ISSUE THREAD

**Issue by matzew** [knative/eventing-contrib#911]
## Proposed Changes
* :gift: Use reconciler gen to implement strongly typed reconcilers.
* 🧽 lots of cleanup around requeue.
* 🧽 lots of cleanup around error events.

See as an example: https://github.com/knative/eventing/pull/2540 

/assign @lberk

**Comment by matzew** [comment]
I guess... we first need to update pkg ... ?

**Comment by n3wscott** [comment]
yes we need pkg updated.

**Comment by matzew** [comment]
@lberk   can you do that first ?

**Comment by lberk** [comment]
pkg update PR in #919

**Comment by lionelvillard** [comment]
/label source/kafka
(testing)

**Comment by lberk** [comment]
/label area/Kafka
(perhaps?)

**Comment by matzew** [comment]
works :-) @lberk @lionelvillard

**Comment by lberk** [comment]
Fixed in https://github.com/knative/eventing-contrib/pull/937
