### ISSUE TITLE
Prune eventing-contrib/pkg/channel

### ISSUE THREAD

**Issue by slinkydeveloper** [knative/eventing-contrib#974]
eventing-contrib/pkg/channel contains a duplicate of the code that now lives in https://github.com/knative/eventing/tree/master/pkg/channel, still used by `NatssChannel`, we should prune it

/help

**Comment by pierDipi** [comment]
Hi @slinkydeveloper, I would like to work on this issue. 
However, as far as I know, if we merge the PR #1008 we will be able to completely remove `eventing-contrib/pkg/channel`. 
Is this issue still relevant?

**Comment by slinkydeveloper** [comment]
Let's merge #1008 and then you can remove this one with another PR.
