### ISSUE TITLE
kafkasource receive-adapter stops partition consumer after a few minutes

### ISSUE THREAD

**Issue by guimou** [knative/eventing-contrib#999]
**Describe the bug**
I created a KafkaSource object, consuming a Kafka topic and forwarding it (sink) to a KNative Service. It works well at first, consuming topic and passing the message to the Service. But after some time, without any new message to the topic, so being supposedly "idle", I get this in the logs:
```
{"level":"error","ts":"2020-03-06T22:32:00.659Z","logger":"kafkasource","caller":"adapter/adapter.go:153","msg":"An error has occurred while consuming messages occurred: ","stacktrace":"knative.dev/eventing-contrib/kafka/source/pkg/adapter.(*Adapter).Start.func3\n\tknative.dev/eventing-contrib/kafka/source/pkg/adapter/adapter.go:153"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 7"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 8"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 9"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 1"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 2"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 6"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 3"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 5"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 4"}
{"level":"info","ts":"2020-03-06T22:32:00.796Z","logger":"kafkasource","caller":"kafka/consumer_handler.go:90","msg":"Stopping partition consumer, topic: odfi, partition: 0"}
```
So there seem to be some error, but no detail. It says "while consuming messages" but I guess it's a generic message as there are no new messages incoming.

 **Expected behavior**
The receiver-adapter should not stop the consumers and continue to receive messages.

 **To Reproduce**
KafkaSource definition:
```
apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: odfi-split
  namespace: ach
spec:
  consumerGroup: odfi-split
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: merchant-upload
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: odfi-split
```

 **Knative release version**
v0.13

 **Additional context**
OCP 4.3.1, AMQStreams Operator 1.3.0, OpenShift Serverless Operator 1.4.1, KNative Eventing Operator 0.12.0, KNative Kafka Operator 0.12.1

**Comment by guimou** [comment]
Before spending too much time on this: I reinstalled AMQ Streams from scratch yesterday, recreated topics with only 3 partitions, and so far, so 15 hours it's still working...

**Comment by slinkydeveloper** [comment]
@guimou it's not the first time that I heard this issue, sounds like something we didn't understood when we integrated kafka using the library sarama. I probably need to dig a little bit more inside their documentation, probably there is some "idle" timeout or some policy to reconnect after the tcp connection break, but i'm not sure

**Comment by guimou** [comment]
@slinkydeveloper OK. If you want me to run some tests just reach out, it's a permanent Lab cluster.

**Comment by slinkydeveloper** [comment]
Ok I've found that it looks like this happens if the connection to kafka broker dies (even for a few seconds)

**Comment by guimou** [comment]
That would make my day if we can figure it out. Right now I have a cron job
to kill the pod, which then gets respawned. Not an elegant solution...
Again, tell me if I can help debugging this.
